### PR TITLE
INFO message for camera make/model/readout

### PR DESCRIPTION
**Pull request by Saijin-Naib**
This currently prints once per image in the Task so it gets noisy on the console.
image
I could use some help cleaning this up, if possible.

### CODE REVIEW

**Comment by pierotofy** [comment]
There; how's this one? https://github.com/OpenDroneMap/ODM/pull/1486/commits/4a9ca4c28332f93c8742dc89067864fa742449ed

**Comment by Saijin-Naib** [comment]
Beautiful, thank you so much! I was really struggling, haha.

The only other thing I can think of at this juncture that I don't know how to handle would be mixed-camera Tasks and ensuring that each camera is represented once by the appropriate WARN/INFO message.

So for instance if I had a Task that had TeraCube, GoPro, and Fuji data, I'd expect to see two INFO messages (TeraCube and GoPro) and one WARN (Fuji).

Does your fix address that mixed-camera usecase?

**Comment by pierotofy** [comment]
> Does your fix address that mixed-camera usecase?

It does!

**Comment by Saijin-Naib** [comment]
I'm totally happy with this! If you're happy (and the CI/CD is happy) can we press merge?

**Pull request merged**
