### PR TITLE
add dmpdtm.py

### PR DESCRIPTION
**Pull request by smathermather**
Pull request with the intent of integrating some of the magic of DMPdtm from Josh @vonnonn's adaptation of Brad Chambers implementation of Mungus et al., 2014
https://github.com/vonnonn/poodles/blob/main/DMPdtm.py

### CODE REVIEW

**Comment by pierotofy** [comment]
Nice! I wonder if there's a way to refactor this to not need panda/pdal python bindings. I'll have to set some time aside to look into this, unless somebody else beats me to it.

**Comment by smathermather** [comment]
> Nice! I wonder if there's a way to refactor this to not need panda/pdal python bindings. I'll have to set some time aside to look into this, unless somebody else beats me to it.

You definitely have a couple geo folks (me and Josh) pretending to do CS here. MVP in my mind is having this as an option, as the results are so staggeringly better than any other PC filtering option. Help refactoring to remove any necessary dependencies very much appreciated.

**Comment by smathermather** [comment]
Looks like pdal changed how it's handling Reader. I'll likely rewrite as pipeline for reading and filtering.

**Comment by vonnonn** [comment]
Dang, wish I could help. I'll back in the saddle Sunday evening.

**Comment by pierotofy** [comment]
#1565 brings in the pdal python bindings (and pandas), so perhaps it will make it easier to integrate this.

**Comment by smathermather** [comment]
And pandas?! Oh yeah... . Ok, lets get this done.

**Comment by smathermather** [comment]
For now I'll close this in favor of the other classification work. At some point I'll compare the two.

**Pull request closed without merging**
