### PR TITLE
Blender 360 and VR video scripts

### PR DESCRIPTION
**Pull request by pulquero**
Following on from the photo script, here is the video script.

### CODE REVIEW

**Comment by pierotofy** [comment]
That's very cool! Do you have an example video output generated from this script? Just curious to see.

**Comment by pulquero** [comment]
Nothing really decent because it takes a long time to render on my machine.

**Comment by smathermather** [comment]
Sorry this is taking so long to test. I need to set up a big machine for this, which won't happen for another couple of weeks. But, for the record, I'm really excited to try this out.

**Comment by pierotofy** [comment]
I'm going to merge this since it's a contrib module, it doesn't break anything and will incentive people to test it out. Thanks for the PR @pulquero!

**Comment by dakotabenjamin** [comment]
TY Piero. Apologies for delaying the merge

**Comment by smathermather** [comment]
I can't wait to test this. I'm hoping we'll have a machine for this next year... .

**Pull request merged**
