### PR TITLE
Add kmz output

### PR DESCRIPTION
**Pull request by smathermather**

### CODE REVIEW

**Comment by pierotofy** [comment]
Good start! It's missing the entry in `config.py` and there's one too many `%s` in the GDAL command. Make sure to try running it once to verify it works.

**Comment by smathermather** [comment]
Yeah, meant to mark it as draft, as I wrote it quickly and haven't tested yet.

Yup: extra arg in there from the copy pasta. :)

**Comment by smathermather** [comment]
Screenshot from 2021-01-07 11-24-17

**Comment by smathermather** [comment]
Screenshot from 2021-04-15 18-35-56

**Comment by smathermather** [comment]
Feel free to squash and merge at will. :D

**Comment by coreysnipes** [comment]
Holy quick turnaround, Batman!  
Nice work.

**Comment by smathermather** [comment]
One important question though: do we autobuild flags on docs yet, or do I need to do a quick pull request over there. You'd think I'd remember...

**Comment by pierotofy** [comment]
Nice addition!

I made a pull request time ago in the docs that would auto-generate the https://docs.opendronemap.org/arguments.html page, but the auto-build was broken then. Not sure if it has been fixed.

**Pull request merged**
