### PR TITLE
Update photo.py

### PR DESCRIPTION
**Pull request by summitbri**
Pitch adjustment for DJI M300 P1 sensor

### CODE REVIEW

**Comment by pierotofy** [comment]
Hey @summitbri :wave: thanks for the PR. How did you compute this adjustment? Do you have a reference photo we can use to verify the correctness?

**Comment by summitbri** [comment]
Sure, please refer to this thread
SFM Triangulation for DJI M300 Zenmuse P1 - ODM - OpenDroneMap Community<https://community.opendronemap.org/t/sfm-triangulation-for-dji-m300-zenmuse-p1/13453/2>

Reference photo is here:  DJI_20221016140529_0067.JPG<https://topomatters-my.sharepoint.com/:i:/p/brian_yohn/EbQ007jQHd9LmPKZ8Vz88IwB8VTTtm4Xo3ihV-8IOm0eMA?e=Na0bpH>

**Comment by pierotofy** [comment]
The pitch actually seems correct.

Raw value: -90

This is executed from line 451:

```
if self.camera_make.lower() in ['dji', 'hasselblad']:
                            self.pitch = 90 + self.pitch
```

Thus:

`pitch = 90 + (-90) = 0`
`Pitch: 0 --> nadir camera`

(Which is the reference photo)

Adding this extra proposed change will change the pitch to `+90` (incorrect).

The issue might be elsewhere?

**Comment by summitbri** [comment]
I mis-understood that code, thought it was looking for just hasselblad across the dji rows.  Must be some other reason we're not picking up YPR for this sensor.

**Comment by summitbri** [comment]
@pierotofy why does the first line of this code block grab the FlightYawDegree and not GimbalYawDegree?

                # OPK
                self.set_attr_from_xmp_tag('yaw', xtags, ['@drone-dji:FlightYawDegree', '@Camera:Yaw', 'Camera:Yaw'], float)
                self.set_attr_from_xmp_tag('pitch', xtags, ['@drone-dji:GimbalPitchDegree', '@Camera:Pitch', 'Camera:Pitch'], float)
                self.set_attr_from_xmp_tag('roll', xtags, ['@drone-dji:GimbalRollDegree', '@Camera:Roll', 'Camera:Roll'], float)

**Comment by pierotofy** [comment]
I think during testing with various Phantom 3 Advanced datasets the GimbalYawDegree wasn't reporting the expected/proper value, although this was quite a while ago, so I'm not 100% sure.

**Pull request closed without merging**
