### PR TITLE
Modify Camera option

### PR DESCRIPTION
**Pull request by JangWooCheon**
About modifying camera ( Sony ILCE-7M2) sensor size

### CODE REVIEW

**Comment by dakotabenjamin** [comment]
You are modifying depreciated code that will be removed in the next update. See #237

**Comment by smathermather** [comment]
@dakotabenjamin -- should we include in current code though (with corrections -- looks like there are some typos)?

**Comment by dakotabenjamin** [comment]
No because the current code uses the mapillary json file, unless for some reason you need to use bundler.

**Comment by smathermather** [comment]
:+1:

**Pull request closed without merging**
