### PR TITLE
ODM 2.0 - Migration to 18.04, Python 3.6, new features, bug fixes

### PR DESCRIPTION
**Pull request by pierotofy**
This is a major PR (not ready yet, opening a draft to allow early feedback/contributions) that:
 * Upgrades the target OS to Ubuntu 18.04
 * Upgrades Python to version 3.6
 * Upgrades PDAL/Entwine to the latest release

Tentatively I will also try to upgrade OpenSfM to the newest version, which has many new speed improvements, although it's still in active development, so I might hold off on that for a bit until the codebase stabilizes.

Due to possible breaking changes for some users that run this natively (Python 2 vs Python 3 chaos), this will mark a `2.0` release. I will try my best not to break things and provide a smooth path to upgrade.

:clinking_glasses:

### CODE REVIEW

**Comment by Saijin-Naib** [comment]
Does this warrant a quadratik fund?

**Comment by pierotofy** [comment]
No need, this is a necessary upgrade.

**Comment by pierotofy** [comment]
Should fix (or at least improve substantially) #1113  and #1090

image

(credits to `edt` author)

**Comment by pierotofy** [comment]
Guarantees #1110 will never occur (I couldn't reproduce it, but should be fixed).

**Comment by pierotofy** [comment]
Closes #834

**Comment by pierotofy** [comment]
Implements #983

**Comment by smathermather** [comment]
> Implements #983

Whoa!

**Comment by pierotofy** [comment]
Implements #897 

People can now include a `geo.txt` file that specifies/overrides the camera center coordinates without having to fiddle with exiftool to set GPS tags.

Format:

```
EPSG:<code> or <+proj definition>
image_name geo_x geo_y [geo_z] [omega (degrees)] [phi (degrees)] [kappa (degrees)] [horz accuracy (meters)] [vert accuracy (meters)]
```

Use via `--geo <path_to_file>`. Works like the `--gcp` option.

**Comment by pierotofy** [comment]
```
The accuracy commitments do not apply to GPS devices, but rather to the signals transmitted in space. For example, the government commits to broadcasting the GPS signal in space with a global average user range error (URE) of ?7.8 m (25.6 ft.), with 95% probability. Actual performance exceeds the specification. On May 11, 2016, the global average URE was ?0.715 m (2.3 ft.), 95% of the time.
```
https://www.gps.gov/systems/gps/performance/accuracy/#how-accurate

Perhaps `10` might be a more conservative change, while still improving results.

**Comment by pierotofy** [comment]
Image masks support for 3D:

image

image


image

**Comment by pierotofy** [comment]
Aaand... image masking for orthophotos:

image

**Comment by pierotofy** [comment]
To add a mask, simply create a new image:

`<filename>_mask.JPG` (make sure to match the extension, including uppercase/lowercase)

For example, `DJI_0018.JPG` can have a mask by creating a `DJI_0018_mask.JPG` file and include that in the list of images.

**Comment by Saijin-Naib** [comment]
Is it possible to use PNG, BMP, or another lossless image format for the mask?

**Comment by pierotofy** [comment]
Currently the extension must match that of the input image.

**Comment by gastgit** [comment]
> Implements #897
> 
> People can now include a `geo.txt` file that specifies/overrides the camera center coordinates without having to fiddle with exiftool to set GPS tags.
> 
> Format:
> 
> ```
> EPSG:<code> or <+proj definition>
> image_name geo_x geo_y [geo_z] [omega (degrees)] [phi (degrees)] [kappa (degrees)] [horz accuracy (meters)] [vert accuracy (meters)]
> ```
> 
> Use via `--geo <path_to_file>`. Works like the `--gcp` option.

Tnx for this new feature!
Can CSV be used or only TXT?

**Comment by pierotofy** [comment]
Only TXT. But it's easy to convert from CSV.

**Comment by pierotofy** [comment]
Masks can now use arbitrary extensions (.png, .bmp, .unicorn, .whatever).

**Comment by pierotofy** [comment]
Adds the `--tiles` option to generate static tiles, since NodeODM will no longer be in charge of this.

**Comment by smathermather** [comment]
Good! Tested this weekend without issue. Just forgot to update here... . Looks great, installs easily, processes fine with no noticable issues.

**Pull request merged**
