### PR TITLE
Adding TIFFTAG_* to .tif outputs

### PR DESCRIPTION
**Pull request by stephenwinn16**
Following up on  #1793, I've added steps to the orthophoto and DSM/DTM generation to be able to include TIFFTAG information. In the current commit, I've hardcoded a datetime for testing purposes. I would like this to be replaced by a mean capture time based on the input image metadata (such as the "Capture Start" and "Capture End" that appear e.g. in the PDF report). Would anyone be able to point me to a good place to pull them from during the processing pipeline? 

Additionally, is the ODM version stored somewhere during the processing pipeline? Or should it always be read from the `VERSION` file as in `run.py`?

### CODE REVIEW

**Comment by pierotofy** [comment]
Thanks @stephenwinn16,  note we should probably set the tags in/around https://github.com/OpenDroneMap/ODM/blob/master/stages/odm_postprocess.py#L38 similarly to how we set GCPs metadata.

You could find the precomputed start/end dates in `odm_report/stats.json`, but you have to be careful, because if a report is not generated (when `--skip-report` is used) the file might not be there. If not, you'll have to recompute from utc_time https://github.com/OpenDroneMap/ODM/blob/master/opendm/photo.py#L130 as a fallback.

Yes version is stored in `VERSION`. I would just re-read it, or create a function to read it and then optionally memoize it.

**Comment by stephenwinn16** [comment]
Thanks @pierotofy for the comments. I've moved the lines into the `odm_postprocess` step and read the time information either from the `odm_report/shots.geojson` file or the `images.json` file depending on what exists. 

Do you see any other useful information to include with the [TIFFTAG fields](https://gdal.org/en/latest/drivers/raster/gtiff.html)?

**Comment by pierotofy** [comment]
Thanks @stephenwinn16, I've made some changes to simplify the logic and avoid reading files from disk, I realized we already had a function to read the ODM version and that it was probably faster to read the UTC time from the photos object which is already in memory, I'll run some more tests and merge this shortly. :pray:

**Comment by stephenwinn16** [comment]
Great, more efficient and much cleaner, thank you @pierotofy !

**Pull request merged**
