### PR TITLE
Updated opensfm to include loky fix

### PR DESCRIPTION
**Pull request by pierotofy**
This updates OpenSfM to bring the changes introduced by https://github.com/mapillary/OpenSfM/pull/224. This is a resolution of the hanging process reported multiple times by many users.

https://github.com/OpenDroneMap/OpenDroneMap/issues/660
https://github.com/OpenDroneMap/OpenDroneMap/issues/515
https://github.com/OpenDroneMap/WebODM/issues/147
https://github.com/OpenDroneMap/WebODM/issues/269

### CODE REVIEW

**Review by dakotabenjamin — APPROVED** [review]
Thanks for figuring this out! It works for me, although I've never run into the hanging process issue.

**Comment by dakotabenjamin** [comment]
Might this be related? https://github.com/mapillary/OpenSfM/issues/228

**Comment by pierotofy** [comment]
I think the issue was reported for an earlier version (commands/detect_features.py", line 34 does not match the latest version).

If there are no objections I will merge this in.

**Comment by dakotabenjamin** [comment]
Great, maybe @PeterSprague you can pull this in once it's merged and see if that fixes.

**Pull request merged**
