### PR TITLE
Multispectral support, TIFF support, split-merge speed-ups

### PR DESCRIPTION
**Pull request by pierotofy**
(Edit from smathermather: ready for testing from the less courageous)

Opening a PR to invite very early feedback from courageous ones. :muscle: 

Not stable, bugs are expected.

Adds support for multispectral cameras, TIFF support (8/16bit), speeds up significantly the merge step of point clouds and orthophotos during split-merge. 

https://community.opendronemap.org/t/tiff-multispectral-support/3232/12

If you're on Linux you might also enjoy the new `start-dev-env.sh` script for easy hacking of the ODM codebase.

### CODE REVIEW

**Comment by pierotofy** [comment]
Multispectral split-merge is likely broken.

**Comment by pierotofy** [comment]
Ready for testing :+1:

**Comment by smathermather** [comment]
I think I am obliged to test this... :) . Can you share some data for testing?

Dagnabit I need to get that drone and sensor flying. Waiting for Spring... .

**Comment by pierotofy** [comment]
I've tested this with `MicaSense RedEdge-M` (multi-camera setup) and `MAPIR Survey3 Camera Survey3W_RGN` (16bit) datasets. The mapir images I've found from https://www.mapir.camera/pages/survey3-example-media.

I would expect 8bit/16bit 3-channel TIFF datasets to process fine for most camera models. The ones that will need special attention are the multi-camera setups (eg. Parrot Sequoia & co).

**Comment by pierotofy** [comment]
Worth also testing out the merge time for orthophotos and point clouds during split-merge, you should notice a *significant* speed-up. Need to reprocess the datasets (can't just re-run from merge), we use new intermediate orthophoto results to achieve fast runtime (`orthophoto_cut.tif` and `orthophoto_feathered.tif`)

**Comment by smathermather** [comment]
> Worth also testing out the merge time for orthophotos and point clouds during split-merge, you should notice a _significant_ speed-up.

I almost forgot! That'll be fun to test. Also, I have an incoming sequoia dataset for Australia that should be fun to test.

**Comment by pierotofy** [comment]
OpenDroneMap testing suite passed.

**Comment by pierotofy** [comment]
Hoping to merge these sometimes next week; in case problems are found we can always open future PRs to address them.

**Comment by smathermather** [comment]
> Hoping to merge these sometimes next week; in case problems are found we can always open future PRs to address them.

India and I are working on review today and tomorrow.

**Review by smathermather — COMMENTED** [review]
Gonna miss that kangaroo... but not ambiguous waiting times. :)

**Pull request merged**
