### PR TITLE
Improved orthophotos, added --pc-quality flag

### PR DESCRIPTION
**Pull request by pierotofy**
- [x] Substantially improves orthophoto quality
 - [x] Removes the need for `--texturing-nadir-weight` (removed)
 - [x] Simplifies depthmap resolution selection by introducing `--pc-quality` with four different levels (`low`, `medium`, `high`, `ultra`).

Related discussion: https://community.opendronemap.org/t/upcoming-orthophoto-improvements/5923/4

### CODE REVIEW

**Comment by smathermather** [comment]
What is the implication for mixed resolution images of the `--pc-quality` flag?

**Comment by pierotofy** [comment]
It errs on the safe side by using the largest image available.

Eg: 20 pictures at 2000x1000 and 10 at 5000x2500, with `--pc-quality medium` (factor: 0.25), max depthmap resolution is `5000 * 0.25` = `1250` (so the lower resolution pictures are really processed at ultra).

Note that `--depthmap-resolution` is still available. I just marked it as likely to be removed in the near future (probably at the next v3 release, so it will be a while..).

**Comment by Saijin-Naib** [comment]
With these bins, will the resultant resolution always be "integer" scaled, to help with aliasing artifacts that might get introduced otherwise?

Also, do you think there would be value in allowing manual input of other factors, or possibly adding them, for .75 or possibly 1.0 if someone wants to go crazy-go-nuts?

**Comment by smathermather** [comment]
> It errs on the safe side by using the largest image available.

That's what I was reading. It makes sense, and I can't think of any good alternative that doesn't require more effort.

I'm running a particularly tricky orthophoto through shortly. :D

**Comment by pierotofy** [comment]
Yes it's always an integer. Also, OpenMVS can only process resolutions divisible by power of 2, so even though you choose 1200, if your images can only be processed at 4000 (full), 2000 (half), 1000 (quarter) or 500 ( / 8), the program will process at 2000 (which is the closest, erring on the safe side).

OpenSfM instead will process with any integer resolution.

**Comment by Saijin-Naib** [comment]
> 
> OpenSfM instead will process with any integer resolution.

Awesome, that makes sense. I was thinking about power-of-two, but I was thinking that was just a hold-over from my days with iDTech engines and wasn't a thing anymore 🤣

Is it possible/sensible to tie the resolution between OpenSFM and OpenMVS to the same thing, to ensure it is power-of-two and the same the whole way through?

Or does that not buy us anything?

**Comment by smathermather** [comment]
```git clone https://github.com/pierotofy/ODM
cd ODM
git checkout 221 
docker build --squash -t odm211 .
```


```
docker run -it --rm -v $(pwd)/images:/code/images -v $(pwd)/opensfm:/code/opensfm  -v $(pwd)/odm_georeferencing:/code/odm_georeferencing     -v $(pwd)/odm_orthophoto:/code/odm_orthophoto     -v $(pwd)/odm_texturing:/code/odm_texturing odm221  --mesh-size 100000
...

[INFO]    Writing MVS Textured file in: /code/odm_texturing/odm_textured_model.obj
Traceback (most recent call last):
  File "/code/run.py", line 69, in <module>
    app.execute()
  File "/code/stages/odm_app.py", line 86, in execute
    self.first_stage.run()
  File "/code/opendm/types.py", line 361, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 361, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 361, in run
    self.next_stage.run(outputs)
  [Previous line repeated 4 more times]
  File "/code/opendm/types.py", line 342, in run
    self.process(self.args, outputs)
  File "/code/stages/mvstex.py", line 94, in process
    'nadirWeight': 2 ** args.texturing_nadir_weight - 1,
AttributeError: 'Namespace' object has no attribute 'texturing_nadir_weight'
```

**Comment by pierotofy** [comment]
Uups! Nice catch. And that's why we ask feedback... :)

Should be fixed now.

**Comment by smathermather** [comment]
It's probably me, but pulled the latest:
```
git pull
docker build -t odm211 --no-cache .
docker run -it --rm -v $(pwd)/images:/code/images -v $(pwd)/opensfm:/code/opensfm  -v $(pwd)/odm_georeferencing:/code/odm_georeferencing     -v $(pwd)/odm_orthophoto:/code/odm_orthophoto     -v $(pwd)/odm_texturing:/code/odm_texturing odm221  --mesh-size 100000
```

But no dice:

```
[INFO]    running /code/SuperBuild/src/dem2mesh/dem2mesh -inputFile /code/odm_meshing/tmp/mesh_dsm.tif -outputFile /code/odm_meshing/odm_25dmesh.dirty.ply -maxTileLength 2000 -maxVertexCount 100000 -maxConcurrency 12   
[INFO]    running /code/build/bin/odm_cleanmesh -inputFile /code/odm_meshing/odm_25dmesh.dirty.ply -outputFile /code/odm_meshing/odm_25dmesh.ply -removeIslands -decimateMesh 100000  
[INFO]    Finished odm_meshing stage
[INFO]    Running mvs_texturing stage
[INFO]    Writing MVS Textured file in: /code/odm_texturing/odm_textured_model.obj
Traceback (most recent call last):
  File "/code/run.py", line 69, in <module>
    app.execute()
  File "/code/stages/odm_app.py", line 86, in execute
    self.first_stage.run()
  File "/code/opendm/types.py", line 361, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 361, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 361, in run
    self.next_stage.run(outputs)
  [Previous line repeated 4 more times]
  File "/code/opendm/types.py", line 342, in run
    self.process(self.args, outputs)
  File "/code/stages/mvstex.py", line 94, in process
    'nadirWeight': 2 ** args.texturing_nadir_weight - 1,
AttributeError: 'Namespace' object has no attribute 'texturing_nadir_weight'
```

**Comment by Saijin-Naib** [comment]
I edited the file manually in my WSL2 instance to match the pull, and didn't see anything come up with the variable concerning nadir weight, but it still bombed here:  
```
19:23:50 [App     ] Selecting images for dense reconstruction completed: 170 images (30s646ms)
Estimated depth-maps 170 (100%, 8h46m28s760ms)           [[C
Filtered depth-maps 170 (100%, 12m38s321ms)
Fused depth-maps 100 (58.82%, 1m27s, ETA 1m)...Killed
Traceback (most recent call last):
  File "./run.py", line 69, in <module>
    app.execute()
  File "/code/stages/odm_app.py", line 86, in execute
    self.first_stage.run()
  File "/code/opendm/types.py", line 361, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 361, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 361, in run
    self.next_stage.run(outputs)
  [Previous line repeated 1 more time]
  File "/code/opendm/types.py", line 342, in run
    self.process(self.args, outputs)
  File "/code/stages/openmvs.py", line 62, in process
    system.run('%s "%s" %s' % (context.omvs_densify_path,
  File "/code/opendm/system.py", line 79, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 137
```

**Comment by pierotofy** [comment]
You ran out of memory :+1:

**Comment by Saijin-Naib** [comment]
> 
> 
> You ran out of memory 👍

Anyone feel like buying me 2x32GB DDR4 🤣

What would my rerun-from be in this instance? I assume I can't adjust anything in the job at this point to make it go through... Shame.

**Comment by pierotofy** [comment]
@smathermather  you might have to issue `git pull origin 221`, and check with `git log` that this commit has been included: https://github.com/OpenDroneMap/ODM/pull/1201/commits/6aef1de9359f82c48c505c6deed1b10e844a108b

The first entry from git log should read: `Fix mvstex bug referencing old config parameter`

**Comment by smathermather** [comment]
```
git log | grep 6aef1de
commit 6aef1de9359f82c48c505c6deed1b10e844a108b
```

```
git log
commit 6aef1de9359f82c48c505c6deed1b10e844a108b (HEAD -> 221, origin/221)
Author: Piero Toffanin <pt@masseranolabs.com>
Date:   Thu Nov 12 19:38:13 2020 -0500

    Fix mvstex bug referencing old config parameter
```

**Comment by pierotofy** [comment]
Then it should work because this line:

```
 File "/code/stages/mvstex.py", line 94, in process
    'nadirWeight': 2 ** args.texturing_nadir_weight - 1,
```

Does not exist anymore. :laughing:

**Comment by smathermather** [comment]
Yeah, this is some mysterious docker issue. I am now running natively. ¯\_(ツ)_/¯

**Comment by pierotofy** [comment]
Docker never ceases to surprise me.

**Comment by kikislater** [comment]
> Yeah, this is some mysterious docker issue. I am now running natively. ¯_(ツ)_/¯

There is always an explanation, no mystery ! 
Conflicts between previous running container and updated image should be me more reasonable explanation

**Comment by smathermather** [comment]
Ran on my data. The changes are subtle in my test dateset, but certainly aren't worse, and in many places much improved.

**Review by smathermather — APPROVED** [review]

**Pull request merged**
