### PR TITLE
Output Improvements + Ground Sampling Distance

### PR DESCRIPTION
**Pull request by pierotofy**
This PR includes the changes described in https://github.com/OpenDroneMap/OpenDroneMap/projects/2 along with a new Ground Sampling Distance optimization.

The GSD optimization works as described in https://github.com/OpenDroneMap/OpenDroneMap/issues/858 and requires some changes to OpenSfM, which have been merged in the OpenDroneMap's OpenSfM fork, but haven't been merged into mapillary as of yet (see https://github.com/mapillary/OpenSfM/pull/352).

As part of the GSD optimization we've normalized the resolution units for DEM and orthophoto outputs. We now use the industry de-facto standard of `cm / pixel` all across the board.

We've done extensive testing on this branch, but one final check and review should be done before we merge this into master.

A blog post will follow to describe the details of all changes.

https://github.com/OpenDroneMap/WebODM/issues/517 should be taken care of right after this is merged. 

:clinking_glasses:

### CODE REVIEW

**Comment by smathermather** [comment]
Bam!

**Review by smathermather — APPROVED** [review]
Looking good. Ran a tough dataset through and got reasonable results.

**Comment by dakotabenjamin** [comment]
One note is that this will go into version 0.4 unless you wanted to do a feature freeze while the 0.4-RC is out. I personally don't mind.

**Comment by smathermather** [comment]
Good point. I see no problem with it going right into 0.4. It’s a jump in functionality that’s a good problem to have...

**Comment by pierotofy** [comment]
`0.4` works for me. :+1:

**Pull request merged**
