### PR TITLE
Script to generate 360 panoramic photos

### PR DESCRIPTION
**Pull request by pulquero**
Requires Blender and ExifTool.

### CODE REVIEW

**Comment by dakotabenjamin** [comment]
I think we need to come up with some guidelines for adding these modules to contrib, to keep this looking consistent and clean. As a baseline, I think a readme.md is required. This readme should be set up like this:
```
# Name of module
Short description of what it does

## Requirements

## Usage

## Examples
if needed
```

Is there anything else you think?

**Comment by smathermather** [comment]
PostGIS Extras model has similarities:
https://github.com/postgis/postgis/tree/svn-trunk/extras

**Review by dakotabenjamin — APPROVED** [review]

**Comment by smathermather** [comment]
I can't wait to test!

**Comment by smathermather** [comment]
@pulquero -- any favorite viewer for the output?

Notes on building so far: it doesn't work with the default apt-get installed Blender but works great with the binary downloaded from https://blender.org. Otherwise, it was really easy to set up.

**Comment by pulquero** [comment]
For viewers, I use Google photos on Android, or Samsung Gear VR or publish on Facebook.

I'm currently testing a script to do the video equivalents. You'll be able to reconstruct fly/drive/walk-thrus. I can see that being useful for doing planning with.

**Pull request merged**
