### PR TITLE
Add --matcher-order

### PR DESCRIPTION
**Pull request by pierotofy**
Ref https://github.com/OpenDroneMap/ODM/pull/1651

### CODE REVIEW

**Comment by kikislater** [comment]
@pierotofy 
matcher-order is not present in docs: https://docs.opendronemap.org/arguments/

**Comment by pierotofy** [comment]
Ah, yes it should probably be added (interested in opening a PR?) https://github.com/OpenDroneMap/docs

**Comment by Saijin-Naib** [comment]
I'll get this updated on the docs tonight 😎

**Comment by kikislater** [comment]
Thanks @Saijin-Naib 
I didn't have time, next time may be !

**Comment by Saijin-Naib** [comment]
No worries! I'm supposed to be on top of this better 😬

**Pull request merged**
