### PR TITLE
Thermal mapping for DJI M2EA

### PR DESCRIPTION
**Pull request by holyCowMp3**
Hi there! 

Recently I tried to stitch photos from my DJI M2EA drone into ODM to analyze one of my solar stations. 
Creating orthophotos only worked when I was processing stations without radiometric calibration and the pictures were seen as normal JPEGs instead of RJPEG, so I decided to improve ODM a bit)
Added support of M2EA radiometric calibration improved the quality of the result ortophoto, and also help conduct analysis on them!

**Before radiometric calibration with usage photos as JPEG:**
Знімок екрана 2021-12-29 о 17 24 16

**After the calibration:** 
Знімок екрана 2021-12-29 о 17 25 09
Such a great difference! 
The controls at histogram show the temperature values, instead of pixel color!

BUT!
To add support for DJI Zenmuse XT S and DJI Zenmuse H20 Series and FLIR sensors, I need to discuss two problems I encountered during my work.

1) The cameras from FLIR manufacturers store metadata inside the EXIF of the photo in binary form. 
The [thermal_base](https://github.com/detecttechnologies/thermal_base) library reads them using [ExifTool](https://github.com/exiftool/exiftool), but ODM uses [exifread](https://github.com/ianare/exif-py) instead of [ExifTool](https://github.com/exiftool/exiftool) which does not support such a tag.
2) In order to read data from other DJI sensors - you need to add their [thermal SDK](https://www.dji.com/downloads/softwares/dji-thermal-sdk) to call and pull metadata from DJI thermal photos (already covered by [thermal_base](https://github.com/detecttechnologies/thermal_base)), but for ODM there is a more rational way, and I need a little help on the right way to implement this feature.  

Also, thanks goes to the awesome Open Source creators and developers:
[thermal_base](https://github.com/detecttechnologies/thermal_base) as a base for my improvements :) Thanks, @rsnk96, @mukheshpugal, and @agarwalkunal12 your work is great and so much supportive!

### CODE REVIEW

**Comment by pierotofy** [comment]
Hey @markFieldman :hand: this looks pretty amazing.

1. You could add support for reading the appropriate tags directly to exifread? (the developers there are pretty happy to accept pull requests).

2. Is trickier, we cannot include DJI's SDK due to licensing issues. It may be possible to extend thermal_base to support more sensors (I'm guessing there might be similarities between sensors).

**Comment by holyCowMp3** [comment]
> 2\. Is trickier, we cannot include DJI's SDK due to licensing issues. It may be possible to extend thermal_base to support more sensors (I'm guessing there might be similarities between sensors).

DJI thermal SDK published with MIT license. That is mentioned in license.txt inside SDK sources.
Also I tried to use already existing tools to add this feature, without including side dependencies. So i took some parts from the thermal_base but without inclusion of it

```
...
The following portions of the DJI's Thermal SDK ("Software" referred to in the terms below) are made available to you under the terms of the MIT License provided below.
...
```

**Comment by pierotofy** [comment]
The key word in the phrasing is `portions`. Not all parts of the SDK are MIT licensed, unfortunately.

**Comment by holyCowMp3** [comment]
> The key word in the phrasing is `portions`. Not all parts of the SDK are MIT licensed, unfortunately.

Yes you are right. Did not read carefully

**Comment by holyCowMp3** [comment]
I will dive into this problem and continue to investigate. 
Also, I will open new PR after the new year with FLIR camera support.

**Comment by holyCowMp3** [comment]
This PR ready for review, so I will continue working with FLIR sensors after retrieving dataset with FLIR images

**Comment by holyCowMp3** [comment]
About DJI sensors which are supported only with the usage of their proprietary SDK - I decided to write a custom script that will convert DJI RJPEG into TIFF with thermal data. If tests for that will be successful - I will share it as a file in `contrib/` folder and mention it on README.

**Comment by pierotofy** [comment]
Looks good @markFieldman :pray:  Thanks!

**Comment by JRicardoPC** [comment]
Hello,
I have a M2EA and i recently started to use ODM and i have a lot of problem with the result orthophotos.  For that i started for looking a solution for the calibration of the thermal camera and the generation of the orthophoto, so I found this thread, i watched the code, but I don't know how used in WebODM, or individually. I tried launched directly but doesn't worked.

**Comment by holyCowMp3** [comment]
> 

Hi! You need to enable radiometric calibration parameters in your options during the start of processing RJPG from M2EA.
Example of properties:
```
dem-resolution: 2, pc-quality: high, orthophoto-resolution: 2, dsm: true, auto-boundary: true, dem-resolution: 2, radiometric-calibration: camera
```

**Comment by JRicardoPC** [comment]
Hi! thank you very much for answer. 
Sorry to ask for more help, but what kind of setup do you use? I currently fly at 80 x 80 overlap and 20m height.

**Comment by holyCowMp3** [comment]
> Hi! thank you very much for your answer. Sorry to ask for more help, but what kind of setup do you use? I currently fly at 80 x 80 overlap and 20m height.

This is up to you. You can use a different setup. Need to keep a balance between speed and quality of assessments. For me, better is the distance to an assessed object needs to be in the 25m< range, to keep more details about it.

**Comment by david6096** [comment]
Hi, would you like to share the dataset with me? I want to test ODM with the dataset.
 thanks!! 

@markFieldman

**Comment by theoway** [comment]
> About DJI sensors which are supported only with the usage of their proprietary SDK - I decided to write a custom script that will convert DJI RJPEG into TIFF with thermal data. If tests for that will be successful - I will share it as a file in `contrib/` folder and mention it on README.

@markFieldman Awesome work on adding thermal support! Have you been able to add the script to the `contrib` folder yet?

**Comment by AliFlux** [comment]
Hi, is there any update on adding Thermal/FLIR update to webODM?

**Pull request merged**
