### PR TITLE
Upgrade Bundler + add support for Ceres solver

### PR DESCRIPTION
**Pull request by chris-cooper**
This PR should allow testing of the [CERES solver](http://ceres-solver.org/) in bundler.  The PR itself incorporates a few things so should probably not be merged as-is but split into smaller PRs depending on what you want to incorporate.  Here are the things that changed (and motivation in brackets).
- Use of latest bundler master as base (includes support for CERES).
- Using a patched fork of bundler rather than patching within OpenDroneMap (makes it clearer to developers what actual code is being used).
- Using a git submodule for bundler rather than downloading source as zip (provides a clear link to the version of bundler used which can also be followed in github UI).
- Using symlinks for built bundler binaries/libs (allows easy hacking/rebuilding of bundler).
- Various minor changes to support the above.

To get this working...

1) Manually build/install [CERES](http://ceres-solver.org/) on your OpenDroneMap machine.
2) Run install.sh for this branch of OpenDroneMap.
3) Try running on some datasets.

If this works you should see CERES mentioned in the logs...

```
# reconstruction-with-image-size-2400/bundle/out
...
[Ceres] num_points = 3858
[Ceres] num_cameras = 2
[Ceres] num_params = 11592
[Ceres] num_projections = 7716
[Ceres] Using CHOLMOD
....
```

The boruszyn_kap dataset was used for testing on an "Intel® Core™ i7-3537U CPU @ 2.00GHz × 4".  Results with/without CERES (disable CERES by comment the --use_ceres flag in run.pl).

```
# Without CERES
[BundleAdjust] Bundle adjustment took 543.128s

# With CERES
[BundleAdjust] Bundle adjustment took 156.540s
```

It seemed to be giving valid results in both cases.  I'm still new to theses codebases so there's a chance my results are incorrect.

### CODE REVIEW

**Comment by smathermather** [comment]
Hi Chris, this looks quite promising. Can you include in the pull request modifications to the installer for installing CERES?

**Comment by Fi156** [comment]
I tried it yesterday!
Good news: Ceres worked after the compilation.
A step by step guide can be found here: http://ceres-solver.org/building.html#linux
The test problem from Ceres worked without an error.

But to my understanding Bundler has not used the Ceres solver afterwards. 
The word "Ceres" can not be found in the "out" document of bundler.
I uploaded the file here (23mb):
https://drive.google.com/file/d/0Bw6KvAgIXTLpVnR6dGJ2WldQOE0/view?usp=sharing

I also tried to compile the latest version of Bundler\* by myself with Ceres enabled manually. And copied the binaries to [ODM_ROOT]/bin/ with no effect.

Any suggestions?
- = https://github.com/snavely/bundler_sfm

**Comment by chris-cooper** [comment]
Sure, I'll look into it @smathermather.  W.r.t. the patched bundler (if you think this is the way to go), can I suggest you create your own fork of bundler_sfm under OpenDroneMap.  You should be able to pull from my fork and push to yours.  Then I'll use that as the submodule in this PR and you'll be able to manage ongoing maintenance.

@Fi156, I'm not sure what's happening in your case as I assume this worked for @smathermather.  Can I suggest you wait until we've added Ceres build to this PR then try again from a clean slate?

**Comment by chris-cooper** [comment]
OK this should be ready for another look.  I tried to pull in Ceres as a git submodule, but [there is an issue with building it that way](https://github.com/ceres-solver/ceres-solver/issues/164).  I've instead done pretty much the same as the [OpenSfM PR](https://github.com/OpenDroneMap/OpenDroneMap/pull/50).

**Comment by Fi156** [comment]
It was completely my fault.
Your code works fine.

approx. 50 images, AMD FX 8320 (4 Cores):
without Ceres: 40 min
with Ceres: 20min

Thanks!

**Comment by smathermather** [comment]
Cool @chris-cooper. I'll give this a whirl tomorrow.

**Comment by chris-cooper** [comment]
Fyi [they just fixed Ceres](https://github.com/ceres-solver/ceres-solver/issues/164) so I've switched back to pulling it in as a git submodule.

**Comment by smathermather** [comment]
Awesome. I think @dakotabenjamin is going to be playing with this pull request soon.

**Comment by dakotabenjamin** [comment]
Running the copr dataset on a vagrant machine (4 cores of an Intel Zeon):
From bundle/out:
with ceres: 
`[BundleAdjust] Bundle adjustment took 1261.721s`
without ceres:
`[BundleAdjust] Bundle adjustment took 8819.091s`

It seemed to take a longer time than usual even without ceres, so I'm gonna reboot the vagrant machine with 6 cores and run again with other datasets.

**Comment by dakotabenjamin** [comment]
seneca:
without ceres:
`[BundleAdjust] Bundle adjustment took 187.996s`

with ceres: 
`[BundleAdjust] Bundle adjustment took 185.038s`

---

caliterra:
without ceres:
`[BundleAdjust] Bundle adjustment took 1657.860s`

with ceres:
`[BundleAdjust] Bundle adjustment took 721.358s`

**Pull request merged**
