### PR TITLE
Updates for 16.10 compatibility

### PR DESCRIPTION
**Pull request by dakotabenjamin**
Updates: 
- VTK5 -> VTK6
- OpenCV 2.4.11 -> Opencv 2.4.13.3
- Ecto -> 0.6.12

Fixes some compatibility issues with odm_meshing

See: #659 #410 #556 

EDIT: still working out kinks for 17.04

### CODE REVIEW

**Comment by tomasholderness** [comment]
+1 for this PR as it also fixes build issues for Ubuntu 16.04.03 (see https://github.com/OpenDroneMap/OpenDroneMap/issues/556).

**Comment by smathermather** [comment]
Do we need testing on this, @dakotabenjamin?

**Comment by dakotabenjamin** [comment]
This is outdated, so more than just testing needs to be done.

**Comment by pierotofy** [comment]
I will close this since the changes regard files that do not exist in the pipeline anymore. We'll focus on adding support for Ubuntu 18.04 in the very near future.

**Pull request closed without merging**
