### PR TITLE
Optimize disk space

### PR DESCRIPTION
**Pull request by pierotofy**
This PR adds support for a new flag, `--optimize-disk-space`, which eliminates heavy intermediate files as the pipeline runs.

Pros: process larger datasets with less HD space available.
Cons: cannot restart the pipeline from an intermediate stage.

### CODE REVIEW

**Comment by smathermather** [comment]
Brilliant.

**Comment by smathermather** [comment]
Can WebODM run on intermediate products? If not, should this be default in WebODM?

**Comment by pierotofy** [comment]
WebODM can run on intermediate products, if the processing node is local, for up to 2 days (before NodeODM purges intermediate results). I'd let users decide whether to use it or not.

**Comment by smathermather** [comment]
Ahh, I wondered why those options are exposed there. I'm never using a local node... . Maybe I should change that.

**Comment by pierotofy** [comment]
I should mention, this can be a remote node too, it just need *not* to use S3 uploads (like webodm.net). If the options are exposed, it should be able to use it (they are hidden when this can't be used).

**Pull request merged**
