### PR TITLE
Lidar2dems

### PR DESCRIPTION
**Pull request by pierotofy**
Still needs testing and two repos (lidar2dems and gippy) need to be moved under the OpenDroneMap org before merging.

This is an update that integrates the lidar2dems package into OpenDroneMap. New command line options:

```
  --dtm                 Use this tag to build a DTM (Digital Terrain Model,
                        ground only) using a progressive morphological filter.
                        Check the --dem* parameters for fine tuning.
  --dsm                 Use this tag to build a DSM (Digital Surface Model,
                        ground + objects) using a progressive morphological
                        filter. Check the --dem* parameters for fine tuning.
  --dem-gapfill-steps <positive integer>
                        Number of steps used to fill areas with gaps. Set to 0
                        to disable gap filling. Starting with a radius equal
                        to the output resolution, N different DEMs are
                        generated with progressively bigger radius using the
                        inverse distance weighted (IDW) algorithm and merged
                        together. Remaining gaps are then merged using nearest
                        neighbor interpolation. generation. Default=4
  --dem-resolution <float>
                        Length of raster cell edges in X/Y units. Default: 0.1
  --dem-maxangle <positive float>
                        Points that are more than maxangle degrees off-nadir
                        are discarded. Default: 20
  --dem-maxsd <positive float>
                        Points that deviate more than maxsd standard
                        deviations from the local mean are discarded. Default:
                        2.5
  --dem-approximate     Use this tag use the approximate progressive
                        morphological filter, which computes DEMs faster but
                        is not as accurate.
  --dem-decimation <positive integer>
                        Decimate the points before generating the DEM. 1 is no
                        decimation (full quality). 100 decimates ~99% of the
                        points. Useful for speeding up generation. Default=1
  --dem-terrain-type <string>
                        One of: FlatNonForest, FlatForest, ComplexNonForest,
                        ComplexForest. Specifies the type of terrain. This
                        mainly helps reduce processing time. FlatNonForest:
                        Relatively flat region with little to no vegetation
                        FlatForest: Relatively flat region that is forested
                        ComplexNonForest: Varied terrain with little to no
                        vegetation ComplexForest: Varied terrain that is
                        forested Default=ComplexForest

```

I've tried to keep these to a minimum while leaving flexibility for parameter tuning.

Something to notice about the new ODMDEMCell class is that I've stopped creating paths in `opendm/types.py`. The pattern of creating a central module for all paths might seem appealing (I've done it myself before in a large project), because the idea is that sometimes in the future we might want to change paths, but in practice 1) this never happens and 2) with IDEs this is as simple as doing a "replace all in files" operation. I have also stopped passing passing command line input parameters via Ecto cells, since we don't really use Ecto's functionality of trickle down parameters from one cell to another, but we simply pass what are a de-facto global variables (args and tree). I access directly args and tree, so I don't have to duplicate a cell's parameter description (those are already specified in `config.py`).

Sample DSM output:

image

### CODE REVIEW

**Comment by pierotofy** [comment]
Note to self: should probably remove the classification step (pmf filter) if the user only needs a DSM, it speeds up things considerably.

**Comment by pierotofy** [comment]
Automated clipping!

image

**Comment by pierotofy** [comment]
@dakotabenjamin @smathermather would you have some time to look over these changes?

We could also fork the https://github.com/pierotofy/lidar2dems and https://github.com/pierotofy/gippy repositories under OpenDroneMap, so that my personal account doesn't have to be referenced in the build files.

**Comment by dakotabenjamin** [comment]
I'm out in the field right now, but if I get back in time today I will look at this. Otherwise I will test and merge tomorrow.
________________________________

**Comment by pierotofy** [comment]
No rush, whenever you have time 😄

**Comment by dakotabenjamin** [comment]
First of all: https://github.com/OpenDroneMap/lidar2dems https://github.com/OpenDroneMap/gippy

**Comment by pierotofy** [comment]
URLs changed

**Comment by dakotabenjamin** [comment]
I ran into this permissions error while trying to install. I'll check on a fresh vm if I get the same error: 
```
-- downloading...
     src='https://github.com/PDAL/PDAL/archive/e881b581e3b91a928105d67db44c567f3b6d1afe.tar.gz'
     dst='/home/dmb2/opendronemap/SuperBuild/download/e881b581e3b91a928105d67db44c567f3b6d1afe.tar.gz'
     timeout='none'
-- downloading...
     src='http://ceres-solver.org/ceres-solver-1.10.0.tar.gz'
     dst='/home/dmb2/opendronemap/SuperBuild/download/ceres-solver-1.10.0.tar.gz'
     timeout='none'
-- [download 0% complete]
-- [download 1% complete]
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-7726.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.

-- [download 2% complete]
ln: failed to create symbolic link '/usr/bin/pdal': Permission denied
CMakeFiles/lidar2dems.dir/build.make:73: recipe for target 'lidar2dems/stamp/lidar2dems-install' failed
make[2]: *** [lidar2dems/stamp/lidar2dems-install] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/lidar2dems.dir/all' failed
make[1]: *** [CMakeFiles/lidar2dems.dir/all] Error 2
```

EDIT: Error still occurs in a fresh VM

**Comment by pierotofy** [comment]
Mm, I'm assuming that the installation should work without sudo?

I've tested in docker, but in docker we run everything as root.

**Comment by pierotofy** [comment]
ps: could I get push rights to the lidar2dems repo?

**Comment by pierotofy** [comment]
@dakotabenjamin I made some changes so that the installation of all lidar2dems files is in the SuperBuild/install directory, then added the necessary code to specify the PATH of the pdal and l2d_* scripts as part of system.run. I'm running a docker build right now, but I think it should work.

**Comment by dakotabenjamin** [comment]
```
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/home/ubuntu/OpenDroneMap/SuperBuild/install/lib/python2.7/dist-packages/test-easy-install-2067.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /home/ubuntu/OpenDroneMap/SuperBuild/install/lib/python2.7/dist-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).
```

Except that dir does exist:
```
ubuntu@ubuntu-xenial:~/OpenDroneMap$ ls SuperBuild/install/lib/python2.7/dist-packages/
catkin  catkin-0.6.16.egg-info
ubuntu@ubuntu-xenial:~/OpenDroneMap$
```

**Comment by pierotofy** [comment]
Are the permissions correct (does your user have write permission to that folder)? Also, could you share the environment you are using for testing (is this a fresh Ubuntu 16.04 machine?)

**Comment by dakotabenjamin** [comment]
In a Vagrant virtual machine. 

```
ubuntu@ubuntu-xenial:~/OpenDroneMap$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
ubuntu@ubuntu-xenial:~/OpenDroneMap$ ls SuperBuild/install/lib/python2.7/dist-packages/ -al
total 16
drwxrwxr-x 3 ubuntu ubuntu 4096 Jun 29 15:10 .
drwxrwxr-x 3 ubuntu ubuntu 4096 Jun 29 15:10 ..
drwxrwxr-x 2 ubuntu ubuntu 4096 Jun 29 15:10 catkin
-rw-rw-r-- 1 ubuntu ubuntu  272 Jun 29 15:10 catkin-0.6.16.egg-info
ubuntu@ubuntu-xenial:~/OpenDroneMap$
```

**Comment by pierotofy** [comment]
I wonder if this is a racing condition. Did you use `make -jX` (with X higher than 1)? What happens if you run with just `make` (no parallelism)?

**Comment by pierotofy** [comment]
So I've just tried on a fresh Ubuntu 16.04 installation, checked out the lidar2dems branch and run:

```
bash configure.sh install
```

No errors, things worked OK. Not sure what to make of it. Tried this on VirtualBox.

**Comment by pierotofy** [comment]
@dakotabenjamin would you be able to share the vagrant machine image?

**Comment by dakotabenjamin** [comment]
How should I share the vagrant machine with you? Do you just need the vagrant file or the whole vm image?

**Comment by pierotofy** [comment]
Maybe the whole VM image? I don’t really have much experience with vagrant, so whichever you think would be most helpful in helping me reproduce the issue.

**Comment by dakotabenjamin** [comment]
[xenial_odm.zip](https://github.com/OpenDroneMap/OpenDroneMap/files/1125636/xenial_odm.zip)

**Comment by dakotabenjamin** [comment]
try that for now. Just run 
```
vagrant up && vagrant ssh
```
when in the dir with the Vagrantfile

**Comment by dakotabenjamin** [comment]
IDK why but it installed fine today

**Comment by pierotofy** [comment]
Yeah I think this might be some sort of racing condition, with faster computers being able to reproduce this sporadically (I'm still retrying the compilation under vagrant, but I have the impression that it will work OK because I have a slow machine).

**Comment by pierotofy** [comment]
@dakotabenjamin I've changed lidar2dems's `install.sh` to check that the dist-packages directory exists prior to trying to install lidar2dems. https://github.com/OpenDroneMap/lidar2dems/blob/master/install.sh

This should take care of the problem even when the race condition scenario occurs.

**Comment by pierotofy** [comment]
@dakotabenjamin let me know if you need further help testing this. We might want to expose the --max_window_size and --max_distance parameters for the DTM classification in the future, but I think this might be a good starting point.

**Comment by dakotabenjamin** [comment]
I'm going to do more testing than normal on this one because I think it's an important new feature and I want to make sure it works well on a breadth of data

**Pull request merged**
