### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by Saijin-Naib**
Alphabetized list for ease of editing.

Bumped many modules to current/latest, as tested working in local WSL2 environment.

### CODE REVIEW

**Comment by pierotofy** [comment]
Did this pass the OATS test suite? It's a large number of upgrades.

**Comment by Saijin-Naib** [comment]
No, just my test data.

I'll do that and follow up

How do I point OATS at my local /code/ directory to test, instead of having it pull/use the opendronemap/odm:latest docker image?

**Comment by pierotofy** [comment]
After building your own docker image with your changes:

```
docker build -t opendronemap/odm:myfork .
```

Use the `--tags myfork` parameter from `./run` in OATS to use your tagged image.

**Comment by Saijin-Naib** [comment]
Got OOM'd fairly early in Sheffield's Cross, but prior datasets look reasonable to me.

```
root@GreenMachine:~/oats# ./run --image_name synper311/odm --tags edge all
 INFO[2020-11-15T11:21:48.724628100-05:00] shim containerd-shim started                  address=/containerd-shim/c2b351385c91f0b7fe4d4407a31db826219f4a127387b00f7d9a7aa39b9135c4.sock debug=false pid=7332 1/1
INFO[2020-11-15T11:25:46.617302800-05:00] shim reaped                                   id=8a1ac57280593a1a70d814759427110eb8118712722e289a317d60abef2b5268
INFO[2020-11-15T11:25:46.627641000-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T11:25:51.930510800-05:00] shim containerd-shim started                  address=/containerd-shim/6c25ed71c4451d8994c2fd84d1c651ea1242d0ac6388bae0a64ffa598cd73101.sock debug=false pid=9918
INFO[2020-11-15T11:25:52.486897600-05:00] shim reaped                                   id=691c6e950baf73a045068568bef08ae0854d3dc914613ebaf185f912b1dbe9db
INFO[2020-11-15T11:25:52.497262800-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ default with dsm

1 test, 0 failures
 INFO[2020-11-15T11:26:13.293515500-05:00] shim containerd-shim started                  address=/containerd-shim/02901bc77c4ef1d1cf7eb4c93084563a12215b1bc77347a11515e46c818dfcaa.sock debug=false pid=104841/2
INFO[2020-11-15T11:30:32.285742100-05:00] shim reaped                                   id=31ad284e7d8631ebdb3d695590f7e0e7002eae005d42e897c002acc653446f73
INFO[2020-11-15T11:30:32.296209300-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T11:30:42.075283400-05:00] shim containerd-shim started                  address=/containerd-shim/d7c75055558df1503b085e58e886b63a9013fd9a19b474a8bff8c61e50188fe3.sock debug=false pid=14070
INFO[2020-11-15T11:30:42.684157100-05:00] shim reaped                                   id=b63dbe09faa93d7081ea5d637e8446f7ac401cf5d2aa4737f95695cf84da4e94
INFO[2020-11-15T11:30:42.694557100-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ default with dsm and dtm
 INFO[2020-11-15T11:30:51.364771300-05:00] shim containerd-shim started                  address=/containerd-shim/6a366bc014b6654e6b24a8a88df0e566f806b1866f70710e292fb928e12fd4b6.sock debug=false pid=14297
INFO[2020-11-15T11:32:48.119498400-05:00] shim reaped                                   id=a5533efb9ef8dafea4a96b2dfe9728c98095524e22f5e94922741688f9f53a1c
INFO[2020-11-15T11:32:48.129765500-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T11:32:51.276759700-05:00] shim containerd-shim started                  address=/containerd-shim/4f75cdb1e94eccc5851184e0c7e23bd9a3fa6f000220d6e615bf899c84782c1e.sock debug=false pid=15233
INFO[2020-11-15T11:32:51.878717300-05:00] shim reaped                                   id=9c3f27c42a76a1bae2bfdb03888eae58f31c0906c85636b85ebab13a9ec9e2de
INFO[2020-11-15T11:32:51.888918900-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ fast orthophoto

2 tests, 0 failures
 INFO[2020-11-15T11:33:00.581477000-05:00] shim containerd-shim started                  address=/containerd-shim/c67074c297194c63c91dc08b1fe4446b605fb5c8dc9791894f0f2aaaeeaec3e5.sock debug=false pid=15586
INFO[2020-11-15T11:34:40.393744200-05:00] shim reaped                                   id=8fb7b6af087eb55421530e43204847fb1c60386c6e6da8777901f26f0b8f3ec4
INFO[2020-11-15T11:34:40.403922500-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T11:34:44.970693100-05:00] shim containerd-shim started                  address=/containerd-shim/27276a0c1e3588d31f3eba83bb6c19233ec80c599ab740058353354cd1605aa7.sock debug=false pid=16288
INFO[2020-11-15T11:34:45.497225300-05:00] shim reaped                                   id=818126c93211fe69d14d9149cc60e0df8e53bca60d7f4acb2d1db2776a28d0f0
INFO[2020-11-15T11:34:45.507473900-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ fast-orthophoto with mask

1 test, 0 failures
 INFO[2020-11-15T11:34:59.063377200-05:00] shim containerd-shim started                  address=/containerd-shim/156ec48bd8a8a7399554ce6f2b795d79acb3ee2566e50ee31a8ee05ce35fd5cf.sock debug=false pid=16633
INFO[2020-11-15T11:36:50.666493500-05:00] shim reaped                                   id=16ba13293eddc1fb1e7345452c3e525f92790b107bc5b5c2f05d5cd389555112
INFO[2020-11-15T11:36:50.676779000-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T11:36:54.358137500-05:00] shim containerd-shim started                  address=/containerd-shim/012aaddc0a9971357de411219ab2e6398b1e017953f5a620b383ce8c28e2a4ed.sock debug=false pid=18229
INFO[2020-11-15T11:36:54.986927800-05:00] shim reaped                                   id=bf653e9d671a3e94054d0c247d27731108114793eb295bfef7819e4227079cba
INFO[2020-11-15T11:36:54.997235000-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ fast-orthophoto with geo and dsm

1 test, 0 failures
 INFO[2020-11-15T11:37:11.356457000-05:00] shim containerd-shim started                  address=/containerd-shim/1104f84531c7d3f4af5c147d4371bf22940011ac3b2ab4602706bf8d81f647be.sock debug=false pid=18574
INFO[2020-11-15T11:41:52.976657900-05:00] shim reaped                                   id=438aeeb8607fbb76860e096b35399d2a91fe5c8ad097a99e0b17a1d2201e09c2
INFO[2020-11-15T11:41:52.986904200-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T11:42:02.447673100-05:00] shim containerd-shim started                  address=/containerd-shim/7981844ce477bf377e35112e5fa0742c1578b68cbe9d4da897392813b576e412.sock debug=false pid=23663
INFO[2020-11-15T11:42:03.034792300-05:00] shim reaped                                   id=ecd73eab356931728467b7abe00c0fbb6498d158a5c469724a3df208f723188d
INFO[2020-11-15T11:42:03.045062700-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ default

1 test, 0 failures
 INFO[2020-11-15T11:42:03.935895200-05:00] shim containerd-shim started                  address=/containerd-shim/689283283206629d21dcf4f1a7c937e75b718d44772108de38c638a07be4dfd4.sock debug=false pid=23943
INFO[2020-11-15T11:42:05.902622000-05:00] shim reaped                                   id=e4eda0a1764ad55c08916ca05bc8474c6f943998c86cee0f3c4c3e63aadb3da0
INFO[2020-11-15T11:42:05.912991300-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T11:42:08.053233500-05:00] shim containerd-shim started                  address=/containerd-shim/5bb24a7654e6e519a4aeb8b243074699ea95b127cfeea2842e75447bd10a42a6.sock debug=false pid=24060
INFO[2020-11-15T11:42:08.603326500-05:00] shim reaped                                   id=6850d6b4e5b398f87394b77ec6963e85aca8740b932be5325b577c38ae58343f
INFO[2020-11-15T11:42:08.613606300-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ fast-orthophoto with mask

1 test, 0 failures
 INFO[2020-11-15T11:42:09.498532800-05:00] shim containerd-shim started                  address=/containerd-shim/45098971a3f909d7ae2154de3caa30f5e107460e0c9b5f8594c95811c7be5420.sock debug=false pid=24329
INFO[2020-11-15T11:42:11.289531800-05:00] shim reaped                                   id=aa90aef925c3c333b0b7f4b671826405deb2430bfdbec5650fcc1d6629dce72c
INFO[2020-11-15T11:42:11.299873000-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T11:42:13.231216500-05:00] shim containerd-shim started                  address=/containerd-shim/560d0021c5acb06151672981c2e48f62c5ebabbacb2593bc9459d3e221558070.sock debug=false pid=24447
INFO[2020-11-15T11:42:13.994285200-05:00] shim reaped                                   id=489309ec1a953ed82cc3cfaf9e6df29053b2e54ef55188aaceab953ed099e563
INFO[2020-11-15T11:42:14.004560500-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ fast-orthophoto with geo and dsm

1 test, 0 failures
 INFO[2020-11-15T11:42:15.234581300-05:00] shim containerd-shim started                  address=/containerd-shim/40a13aa184ad34633b9033aad4aa51d453f71fb6866f0d907b5c94b22d7d44d7.sock debug=false pid=24718
INFO[2020-11-15T11:42:17.070514300-05:00] shim reaped                                   id=0a61074ee18d946c581b847c16641ac2b403124ac53fa494fdb5c52f5b843259
INFO[2020-11-15T11:42:17.080934500-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T11:42:18.780334700-05:00] shim containerd-shim started                  address=/containerd-shim/f6c1c2a5f622dc84f1c92eb4a40a5689fa9c07d0383057ace88f63cda9b499e2.sock debug=false pid=24835
INFO[2020-11-15T11:42:19.427101700-05:00] shim reaped                                   id=3351e4fde0c4429ada3946f13793583df2f1e46b1e4f5a679df6ed967c138a34
INFO[2020-11-15T11:42:19.437386300-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ default

1 test, 0 failures
 ✗ default with dsm
   (from function `check_download_dataset' in file tests/build/functions.bash, line 82,
    from function `run_test' in file tests/build/functions.bash, line 25,
    in test file tests/build/mica_edge.bats, line 5)
     `run_test "--dsm" "edge"' failed with status 8
 ✗ fast orthophoto
   (from function `check_download_dataset' in file tests/build/functions.bash, line 82,
    from function `run_test' in file tests/build/functions.bash, line 25,
    in test file tests/build/mica_edge.bats, line 11)
     `run_test "--fast-orthophoto" "edge"' failed with status 8

2 tests, 2 failures
 ✗ default with dsm, fast ortho
   (from function `check_download_dataset' in file tests/build/functions.bash, line 82,
    from function `run_test' in file tests/build/functions.bash, line 25,
    in test file tests/build/mica_split_edge.bats, line 5)
     `run_test "--dsm --fast-orthophoto --split 24 --split-overlap 50" "edge"' failed with status 8

1 test, 1 failure
 ✗ default with dsm, fast ortho
   (from function `check_download_dataset' in file tests/build/functions.bash, line 82,
    from function `run_test' in file tests/build/functions.bash, line 25,
    in test file tests/build/mica_split_edge.bats, line 5)
     `run_test "--dsm --fast-orthophoto --split 24 --split-overlap 50" "edge"' failed with status 8

1 test, 1 failure
 INFO[2020-11-15T11:45:13.201376000-05:00] shim containerd-shim started                  address=/containerd-shim/0e56cb219ed5d6fc0eb5d6f4464821d2f83c145568dc507a193285d986d98599.sock debug=false pid=25842
INFO[2020-11-15T12:42:57.282669000-05:00] shim reaped                                   id=9284324d4159db655635b371074956e1ef5296592c316c12e09afd7bb4455f1d
INFO[2020-11-15T12:42:59.842195300-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T12:44:04.411758300-05:00] shim containerd-shim started                  address=/containerd-shim/84d186413559abd9de22d3476e8bb8bc40868b0fc71584fd55d4ad798ed6ee81.sock debug=false pid=1340
INFO[2020-11-15T12:44:05.073917400-05:00] shim reaped                                   id=1ba339ac9c86144dcbce6dc3d69ee8bc29790767b2179ce60e29d7b0a624584f
INFO[2020-11-15T12:44:05.084297300-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ Default options with GCP and DSM

1 test, 0 failures
 INFO[2020-11-15T12:44:33.749092800-05:00] shim containerd-shim started                  address=/containerd-shim/71e48d028666faed6c9044d187d9a625641e8bf60b55cf9cfda0fdeda470ed2e.sock debug=false pid=1680
INFO[2020-11-15T12:53:51.209255800-05:00] shim reaped                                   id=a18843b7cbedc7c3686d7054e5dfed43a8e91613a9633f358c3eb58818fc4c48
INFO[2020-11-15T12:53:51.219595600-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T12:53:58.484555000-05:00] shim containerd-shim started                  address=/containerd-shim/0aade54eb7ea65c2d1541dd01cc27d192f70f1ff6fd333eedc1554de10978417.sock debug=false pid=5358
INFO[2020-11-15T12:53:59.074642200-05:00] shim reaped                                   id=20571303b693f5891d5fafca1c55c208e18af639448f61c7a0ac1d166db0f36d
INFO[2020-11-15T12:53:59.085030000-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ Default options with GCP

1 test, 0 failures
 INFO[2020-11-15T12:55:23.853765800-05:00] shim containerd-shim started                  address=/containerd-shim/5f24dddd8643ace447dfca1f536ac4b345a577579eabea6c96e54019194429c2.sock debug=false pid=5703
INFO[2020-11-15T13:17:35.683601800-05:00] shim reaped                                   id=de09675ff48430df5b4f43dc7af968fd53d62972d2424877478264d0f7b576cc
INFO[2020-11-15T13:17:35.694067800-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T13:17:49.473414300-05:00] shim containerd-shim started                  address=/containerd-shim/f4286e30d6a603523f33ee5cf0170507fc12b5d27c592d30cd17703f21dea83a.sock debug=false pid=10484
INFO[2020-11-15T13:17:50.134133700-05:00] shim reaped                                   id=5c898adbe07b81d6d5c66f9aaf9247da8eb7800cbc3097054ec11546decea14b
INFO[2020-11-15T13:17:50.144468800-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ Default options

1 test, 0 failures
 INFO[2020-11-15T13:18:18.848522900-05:00] shim containerd-shim started                  address=/containerd-shim/e77e6e03814933a8f109bed309ec7dbb13ba2badebbd8266d5933a475ec30bc4.sock debug=false pid=10824
INFO[2020-11-15T13:26:51.960895100-05:00] shim reaped                                   id=1276b2baeaf85c0069e32c51d1d4c5eafd177de8b880c67c00ff95da20307546
INFO[2020-11-15T13:26:51.971314500-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-11-15T13:26:58.028524300-05:00] shim containerd-shim started                  address=/containerd-shim/e78d6640355f5e5ac33bb2dddaac053904fd4ccd8bce735d7d1a751460ef40ba.sock debug=false pid=14699
INFO[2020-11-15T13:26:58.646478500-05:00] shim reaped                                   id=748baa8b5380fdf654c0186873672801ee08d34cb7419e7cb2c2ad7cb4ec5ae3
INFO[2020-11-15T13:26:58.656869100-05:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 ✓ Default options with GCP

1 test, 0 failures
 ✗ Default options
   (from function `check_download_dataset' in file tests/build/functions.bash, line 84,
    from function `run_test' in file tests/build/functions.bash, line 25,
    in test file tests/build/sand_key_edge.bats, line 5)
     `run_test "" "edge"' failed with status 2
   Archive:  ./download.zip
   ab37a9680a8b663263f3af9e9af3131421b01f09
      creating: drone_dataset_sand_key-master/
     inflating: drone_dataset_sand_key-master/DJI_0379.JPG
     inflating: drone_dataset_sand_key-master/DJI_0380.JPG
     inflating: drone_dataset_sand_key-master/DJI_0381.JPG
     inflating: drone_dataset_sand_key-master/DJI_0382.JPG
     inflating: drone_dataset_sand_key-master/DJI_0383.JPG
     inflating: drone_dataset_sand_key-master/DJI_0385.JPG
     inflating: drone_dataset_sand_key-master/DJI_0386.JPG
     inflating: drone_dataset_sand_key-master/DJI_0388.JPG
     inflating: drone_dataset_sand_key-master/DJI_0390.JPG
     inflating: drone_dataset_sand_key-master/DJI_0394.JPG
     inflating: drone_dataset_sand_key-master/DJI_0395.JPG
     inflating: drone_dataset_sand_key-master/DJI_0396.JPG
     inflating: drone_dataset_sand_key-master/DJI_0398.JPG
     inflating: drone_dataset_sand_key-master/DJI_0401.JPG
     inflating: drone_dataset_sand_key-master/DJI_0404.JPG
     inflating: drone_dataset_sand_key-master/DJI_0411.JPG
     inflating: drone_dataset_sand_key-master/DJI_0414.JPG
     inflating: drone_dataset_sand_key-master/DJI_0419.JPG
     inflating: drone_dataset_sand_key-master/DJI_0420.JPG
     inflating: drone_dataset_sand_key-master/DJI_0422.JPG
     inflating: drone_dataset_sand_key-master/DJI_0424.JPG
     inflating: drone_dataset_sand_key-master/DJI_0425.JPG
     inflating: drone_dataset_sand_key-master/DJI_0426.JPG
     inflating: drone_dataset_sand_key-master/DJI_0427.JPG
     inflating: drone_dataset_sand_key-master/DJI_0428.JPG
     inflating: drone_dataset_sand_key-master/DJI_0429.JPG
     inflating: drone_dataset_sand_key-master/DJI_0430.JPG
     inflating: drone_dataset_sand_key-master/DJI_0431.JPG
     inflating: drone_dataset_sand_key-master/DJI_0432.JPG
     inflating: drone_dataset_sand_key-master/DJI_0434.JPG
     inflating: drone_dataset_sand_key-master/DJI_0439.JPG
     inflating: drone_dataset_sand_key-master/DJI_0441.JPG
     inflating: drone_dataset_sand_key-master/DJI_0444.JPG
     inflating: drone_dataset_sand_key-master/DJI_0446.JPG
     inflating: drone_dataset_sand_key-master/DJI_0448.JPG
     inflating: drone_dataset_sand_key-master/DJI_0451.JPG
     inflating: drone_dataset_sand_key-master/DJI_0453.JPG
     inflating: drone_dataset_sand_key-master/DJI_0454.JPG
     inflating: drone_dataset_sand_key-master/DJI_0459.JPG    inflating: drone_dataset_sand_key-master/DJI_0462.JPG
     inflating: drone_dataset_sand_key-master/DJI_0463.JPG
     inflating: drone_dataset_sand_key-master/DJI_0465.JPG
     inflating: drone_dataset_sand_key-master/DJI_0466.JPG
     inflating: drone_dataset_sand_key-master/DJI_0468.JPG
     inflating: drone_dataset_sand_key-master/DJI_0469.JPG
     inflating: drone_dataset_sand_key-master/DJI_0470.JPG
     inflating: drone_dataset_sand_key-master/DJI_0472.JPG
     inflating: drone_dataset_sand_key-master/DJI_0473.JPG
     inflating: drone_dataset_sand_key-master/DJI_0474.JPG
     inflating: drone_dataset_sand_key-master/DJI_0475.JPG
     inflating: drone_dataset_sand_key-master/DJI_0476.JPG
     inflating: drone_dataset_sand_key-master/DJI_0478.JPG
     inflating: drone_dataset_sand_key-master/DJI_0479.JPG
     inflating: drone_dataset_sand_key-master/DJI_0480.JPG
     inflating: drone_dataset_sand_key-master/DJI_0481.JPG
     inflating: drone_dataset_sand_key-master/DJI_0483.JPG
     inflating: drone_dataset_sand_key-master/DJI_0484.JPG
     inflating: drone_dataset_sand_key-master/DJI_0487.JPG
     inflating: drone_dataset_sand_key-master/DJI_0490.JPG
     inflating: drone_dataset_sand_key-master/DJI_0493.JPG
     inflating: drone_dataset_sand_key-master/DJI_0494.JPG
     inflating: drone_dataset_sand_key-master/DJI_0498.JPG
     inflating: drone_dataset_sand_key-master/DJI_0504.JPG
     inflating: drone_dataset_sand_key-master/DJI_0505.JPG
     inflating: drone_dataset_sand_key-master/DJI_0507.JPG
     inflating: drone_dataset_sand_key-master/DJI_0508.JPG
     inflating: drone_dataset_sand_key-master/DJI_0514.JPG
     inflating: drone_dataset_sand_key-master/DJI_0516.JPG
     inflating: drone_dataset_sand_key-master/DJI_0517.JPG
     inflating: drone_dataset_sand_key-master/DJI_0519.JPG
     inflating: drone_dataset_sand_key-master/DJI_0522.JPG
     inflating: drone_dataset_sand_key-master/DJI_0524.JPG
     inflating: drone_dataset_sand_key-master/DJI_0527.JPG
     inflating: drone_dataset_sand_key-master/DJI_0529.JPG
     inflating: drone_dataset_sand_key-master/DJI_0531.JPG
     inflating: drone_dataset_sand_key-master/DJI_0533.JPG
     inflating: drone_dataset_sand_key-master/DJI_0536.JPG
     inflating: drone_dataset_sand_key-master/DJI_0537.JPG
     inflating: drone_dataset_sand_key-master/DJI_0538.JPG
     inflating: drone_dataset_sand_key-master/DJI_0540.JPG
     inflating: drone_dataset_sand_key-master/DJI_0541.JPG
     inflating: drone_dataset_sand_key-master/DJI_0543.JPG
     inflating: drone_dataset_sand_key-master/DJI_0544.JPG
     inflating: drone_dataset_sand_key-master/DJI_0545.JPG
     inflating: drone_dataset_sand_key-master/DJI_0546.JPG
     inflating: drone_dataset_sand_key-master/DJI_0547.JPG
     inflating: drone_dataset_sand_key-master/DJI_0548.JPG
     inflating: drone_dataset_sand_key-master/DJI_0549.JPG
     inflating: drone_dataset_sand_key-master/DJI_0551.JPG
     inflating: drone_dataset_sand_key-master/DJI_0552.JPG
     inflating: drone_dataset_sand_key-master/DJI_0554.JPG
     inflating: drone_dataset_sand_key-master/DJI_0555.JPG
     inflating: drone_dataset_sand_key-master/DJI_0557.JPG
     inflating: drone_dataset_sand_key-master/DJI_0559.JPG
     inflating: drone_dataset_sand_key-master/DJI_0562.JPG
     inflating: drone_dataset_sand_key-master/DJI_0563.JPG
     inflating: drone_dataset_sand_key-master/DJI_0564.JPG
     inflating: drone_dataset_sand_key-master/DJI_0565.JPG
     inflating: drone_dataset_sand_key-master/DJI_0566.JPG
     inflating: drone_dataset_sand_key-master/DJI_0568.JPG
     inflating: drone_dataset_sand_key-master/LICENSE

1 test, 1 failure
 INFO[2020-11-15T13:29:32.357392200-05:00] shim containerd-shim started                  address=/containerd-shim/8997a3c0ec12b40217fc0a5817f10724b9eb324267b7cb89b1ce112b705780b2.sock debug=false pid=15444

[process exited with code 1]
```

**Comment by pierotofy** [comment]
Thanks for testing :+1:

**Pull request merged**
