### PR TITLE
PDF Reports

### PR DESCRIPTION
**Pull request by pierotofy**
Brings the new PDF report generation capabilities of OpenSfM into ODM (with some customizations and additions relevant to ODM).

I'm still evaluating to add a few more things to the report:

- [x] Overlap diagram
- [x] Preview of products (ortho, DEMs)

### CODE REVIEW

**Comment by pierotofy** [comment]
Example report from brighton beach dataset: [report.pdf](https://github.com/OpenDroneMap/ODM/files/5797998/report.pdf)

**Comment by pierotofy** [comment]
Closes #911

**Comment by Saijin-Naib** [comment]
May I just say that I love this, and in addition, I love that the "flow" of the document matches another "standard" product that many are familiar with. It makes it so much easier for my brain to intuit where I want/need to look, and even works great for comparing the reports side-by-side.

**Comment by pierotofy** [comment]
Overlap diagrams:

image
image

**Comment by smathermather** [comment]
Oh yeah!

**Comment by Saijin-Naib** [comment]
> Overlap diagrams:
> 
These are SO incredibly helpful, especially when you're getting familiar with a new platform or collection pattern/workflow. HUGE help, and a huge asset to have in a report. 

I see this helping us diagnose failure to reconstruct issues in the near-term.

**Comment by Saijin-Naib** [comment]
I wonder if the Number Of Returns field might not be appropriate for storing how many images each pixel is present in?

**Comment by pierotofy** [comment]
We're using the `UserData` field.

**Comment by smathermather** [comment]
Yeah, `UserData` keeps folks from using clever hacks. :smile:

**Comment by smathermather** [comment]
Well, that cleans things up a bit both on the dev and the UI side.

**Comment by pierotofy** [comment]
Preview of 2D products:

image

**Comment by Saijin-Naib** [comment]
Any chance we could get a cropline preview? Showing where the extent was prior to crop, maybe as a vector outline on the 2D products example?

Like this, but less awful:  
Inked104633908-dd59b580-566d-11eb-955c-a0e1a0770107_LI

**Comment by pierotofy** [comment]
I'll leave that for a future PR or contribution.

**Comment by pierotofy** [comment]
This is almost done. I just need to figure out how to make things work with split-merge now.

**Comment by Saijin-Naib** [comment]
Love the skip-report flag, and that got me thinking:

Will we have a way from WebODM/ODM-CLI to do a Report-Only run to verify data/settings?

**Comment by pierotofy** [comment]
The report summarizes the results of processing. So you need to actually do the processing to get a report, there's no skipping that :)

Split-merge reporting is proving to be non-trivial... I opened #1227 for a future PR.

**Comment by pierotofy** [comment]
Running some tests and then will release.

**Comment by Saijin-Naib** [comment]
> The report summarizes the results of processing.

So I take it that another commercial product is running the whole processing pipeline, but just against super-low settings to do Report-Only runs?

**Comment by pierotofy** [comment]
I'm not really sure! That's a possibility.

**Pull request merged**
