### PR TITLE
Dev - typo in orthophoto.py

### PR DESCRIPTION
**Pull request by rion-saeon**
Spelling mistake with ODM `orthophoto.py`

```
...`def process(self, inputs, outputs):

    # Benchmarking
    start_time = system.now_raw()

    log.ODM_INFO('Running OMD OrthoPhoto Cell')`...
```

### CODE REVIEW

**Comment by dakotabenjamin** [comment]
You'll want to pull this into dev for now, not master

**Comment by rion-saeon** [comment]
Thanks and apologies,

don't know the GitHub way proper.

Regards,
_Rion Lerm (jnr.)_
(+27) 76 913 8381 (Cell)
(+27) 13 735 3536 (Office)
Ndlovu Node
Phalaborwa Gate, Kruger National Park
South African Environmental Observation Network (SAEON)

Click here to learn about SAEON http://www.saeon.ac.za/saeon-background

**Comment by rion-saeon** [comment]
I closed it,

couldn't manage to change from master to dev?

Regards,
_Rion Lerm (jnr.)_
(+27) 76 913 8381 (Cell)
(+27) 13 735 3536 (Office)
Ndlovu Node
Phalaborwa Gate, Kruger National Park
South African Environmental Observation Network (SAEON)

Click here to learn about SAEON http://www.saeon.ac.za/saeon-background

**Comment by dakotabenjamin** [comment]
Sometimes its easier to just close and open a new one. I understand the struggle

**Pull request closed without merging**
