### PR TITLE
Updated pdal matrix transform pipeline, updated PDAL version

### LINKED ISSUE #522: PDAL pipeline distorts point cloud in certain datasets
Input dataset: https://www.dropbox.com/sh/d28k2p7silx5ows/AAD0jglE7C70DuNFT0zu-xEda?dl=0

Problem happens with either OpenSfM or PMVS.

The resulting `odm_georeferenced_model.ply` point cloud is generated correctly (see below):

image

The `odm_georeferenced_model.ply.las` file generated with `/code/SuperBuild/build/pdal/bin/pdal pipeline -i /var/www/data/53683562-45b6-495e-86d6-f00a22208e68/odm_georeferencing/pipeline.xml --readers.ply.filename=/var/www/data/53683562-45b6-495e-86d6-f00a22208e68/odm_georeferencing/odm_georeferenced_model.ply --writers.las.filename=/var/www/data/53683562-45b6-495e-86d6-f00a22208e68/odm_georeferencing/odm_georeferenced_model.ply.las` however is "striped". See below:

Potree display:

image

CloudCompare display:

image

PLY file: https://ufile.io/08728
LAS file: https://ufile.io/d3d511

### PR DESCRIPTION
**Pull request by pierotofy**
Fixes #522. Upgrades PDAL to include the changes to use double precision in the PLY reader.

### CODE REVIEW

**Comment by dakotabenjamin** [comment]
This will also see improvements in the DEM progressive morphological filter.

**Comment by dakotabenjamin** [comment]
I got this error:
```
[DEBUG]   running /home/dmb2/opendronemap/SuperBuild/build/pdal/bin/pdal pipeline /home/dmb2/ODMProjects/bluffs/odm_georeferencing/dem.json --readers.las.filename=/home/dmb2/ODMProjects/bluffs/odm_georeferencing/odm_georeferenced_model.las --writers.gdal.filename=/home/dmb2/ODMProjects/bluffs/odm_georeferencing/odm_georeferencing_model_dem.tif
PDAL: filters.pmf: Unexpected argument 'extract'.

Traceback (most recent call last):
  File "/home/dmb2/opendronemap/run.py", line 46, in <module>
    plasm.execute(niter=1)
  File "/home/dmb2/opendronemap/scripts/odm_georeferencing.py", line 183, in process
    self.params.gdal_radius)
  File "/home/dmb2/opendronemap/opendm/types.py", line 240, in convert_to_dem
    '--writers.gdal.filename={f_out}'.format(**kwargs))
  File "/home/dmb2/opendronemap/opendm/system.py", line 28, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1

```

Here's my json file: 
```json
{
    "pipeline":[
        "input.las",
    {
        "type":"filters.sample",
        "radius":"1.0"
    },
    {
        "type":"filters.pmf",
        "extract":"true"
    },
    {
        "resolution": 2,
        "radius": 0.5,
        "output_type":"idw",
        "filename":"outputfile.tif"
    }
    ]
}
```

**Comment by dakotabenjamin** [comment]
~~Simply removing the `"extract":"true"` line fixed it~~

Now it doesn't extract... Need to add:
```json
{
  "type":"filters.range",
  "limits":"Classification[2:2]"
}
```

**Comment by dakotabenjamin** [comment]
Here's a patch: 
```
From 1efd7cb859363b505f3a479853b7495d8ae5cb7d Mon Sep 17 00:00:00 2001
From: Dakota Benjamin <dmb2@clevelandmetroparks.com>
Date: Wed, 10 May 2017 15:32:12 -0400
Subject: [PATCH] Update dem pipeline to latest pdal specs

---
 opendm/types.py | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/opendm/types.py b/opendm/types.py
index 6ed5773..54892e9 100644
--- a/opendm/types.py
+++ b/opendm/types.py
@@ -221,8 +221,11 @@ class ODM_GeoRef(object):
                        '        "radius":"{sample_radius}"' \
                        '    }},' \
                        '    {{' \
-                       '        "type":"filters.pmf",' \
-                       '        "extract":"true"' \
+                       '        "type":"filters.pmf"' \
+                       '    }},' \
+                       '    {{' \
+                       '      "type":"filters.range",' \
+                       '      "limits":"Classification[2:2]"' \
                        '    }},' \
                        '    {{' \
                        '        "resolution": {gdal_res},' \
-- 
2.7.4
```

**Comment by pierotofy** [comment]
Thanks for the patch! I committed it. Let me know if you find other issues!

**Comment by dakotabenjamin** [comment]
croppercapture 26

croppercapture 27

**Pull request merged**
