### PR TITLE
Allow use of GCPs, allow EPSG codes, use gdaltranslate for georeferencing

### PR DESCRIPTION
**Pull request by dakotabenjamin**

### CODE REVIEW

**Comment by dakotabenjamin** [comment]
@wildintellect this should fix #298 right?

See line 102
https://github.com/OpenDroneMap/OpenDroneMap/pull/286/files#diff-8c79c9fb06263df6b82480d539a6136eR102

**Comment by wildintellect** [comment]
Ya, that looks like it might fix. Will test.

**Comment by dakotabenjamin** [comment]
@petrasovaa fyi

**Comment by smathermather** [comment]
@petrasovaa -- this specifically addresses the GCP issues in the dev branch.

**Comment by petrasovaa** [comment]
I will report back once I get a chance to test it.

**Comment by smathermather** [comment]
:100:

**Comment by petrasovaa** [comment]
I think the odm_georef call is now correct, but I am still getting 'Fewer than 3 GCPs have correspondences in the generated model.' I was trying to debug it and it is weird that the focal length of the cameras here:
https://github.com/OpenDroneMap/OpenDroneMap/blob/dev/modules/odm_georef/src/Georef.cpp#L779
is 0 for 3 of my 4 GCPs. It seems the 0 comes from the bundler file (opensfm/bundle_r000.out).

**Comment by dakotabenjamin** [comment]
What dataset/what's your GCP file look like?

**Comment by petrasovaa** [comment]
It's my own dataset with over 120 images. I can provide it if needed. The gcp file looks like this:

```
WGS84 UTM 17N
708477.20   3956143.22  111.888 1341    722 dsc01547.jpg
708414.74   3956358.68  115.335 876 1132    dsc01616.jpg
708379.31   3956123.88  112.526 1251    989 dsc01625.jpg
708242.35   3956161.65  111.069 1528    709 dsc01757.jpg
```

The weird thing is that Stephen was trying this dataset (recently at FOSS4GNA) and it worked for him. So I think I am doing something wrong, but I have no idea what. I will probably try again with fresh installation.

**Comment by dakotabenjamin** [comment]
EDIT: Below is a weird bug that happens when you rerun without deleting bad files, which should be removed when the georeferecning cell fails so the rerun doesn't think the bad data is real data. 

I'm working through this with the boruszyn_kap dataset (using gcp_list_wgs84.txt for reference), and found the following:

```
[INFO]    Running ODM Georeferencing Cell
[WARNING] Found a valid georeferenced model in: /images/odm_georeferencing/odm_georeferenced_model.ply
[INFO]    Running ODM Georeferencing Cell - Finished
[INFO]    Running OMD OrthoPhoto Cell
[DEBUG]   running /code/build/bin/odm_orthophoto -inputFile /images/odm_texturing/odm_textured_model_geo.obj -logFile /images/odm_orthophoto/odm_orthophoto_log.txt -outputFile /images/odm_orthophoto/odm_orthophoto.png -resolution 20.0 -outputCornerFile /images/odm_orthophoto/odm_orthphoto_corners.txt
[DEBUG]   Line: PUWG1992

[ERROR]   Could not parse coordinates. Bad CRS supplied: PUWG1992

[WARNING] No geo-referenced orthophoto created due to missing geo-referencing or corner coordinates.
[INFO]    Running ODM OrthoPhoto Cell - Finished
[INFO]    OpenDroneMap app finished - Mon May 16 17:28:56  2016
```

`PUWG1992` comes from the other file, gcp_list.txt, in the repository, which is odd because I specifically referenced the other file in the command arguments. This is a separate issue from yours but I wanted to bring it up here because we are both working in the same area right now.

**Pull request merged**
