### PR TITLE
Enhancement of the triangle to image assignment

### PR DESCRIPTION
**Pull request by geraldmwangi**
Hi, first of all thanks for this project. It saved my day!!
I've made some changes to odm_texturemapping.cpp, specifically the function triangleToImageAssignment(): the optimal camera for a face is determined by the 3 criterions:
1) Visibillity (was there before)
2) NEW: camera with minimal distance to face
3) NEW: camera with minimal angle between viewplane normal and face normal

### CODE REVIEW

**Comment by smathermather** [comment]
Wow! Looks great. Let me do some testing, and then I'll merge the pull request.

**Comment by smathermather** [comment]
Hey @dakotabenjamin -- when you get back online, can you test this?

**Comment by dakotabenjamin** [comment]
Sure thing.

On Friday, June 5, 2015, Stephen Mather notifications@github.com wrote:

> Hey @dakotabenjamin https://github.com/dakotabenjamin -- when you get
> back online, can you test this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenDroneMap/OpenDroneMap/pull/113#issuecomment-109467848
> .

## 

Dakota M. Benjamin
Case Western Reserve University, 2015
dakota.benjamin@gmail.com
dakota.benjamin@case.edu

"And now here is my secret, a very simple secret: It is only with the heart
that one can see rightly; what is essential is invisible to the eye."

**Comment by smathermather** [comment]
Awesome. Thanks @dakotabenjamin.

**Comment by dakotabenjamin** [comment]
I ran @geraldmwangi's fork using the following: "run.pl --resize-to 1200 --end-with odm_texturing" on the seneca dataset. It finished without error, but the textured model was blank. see attached. https://www.dropbox.com/s/pr3kb3q9cnoc2qa/odm_texturing.zip?dl=0

**Comment by dakotabenjamin** [comment]
On second look, the model gives some textures, but only around vertical faces.

**Comment by geraldmwangi** [comment]
On 06/10/2015 02:52 PM, Dakota Benjamin wrote:

> On second look, the model gives some textures, but only around vertical faces.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/OpenDroneMap/OpenDroneMap/pull/113#issuecomment-110739373
> 
> Hi in my code I compute the normals of each face and the angle to the
> normal of each camera plane. I then search for the camera with the
> smallest angle for a particular face. Maybe the normals in your dataset
> are flipped compared to my data. Can you change

double cos=normal.z/norm; to double cos=-normal.z/norm;

in line 555 of OdmTexturing.cpp and send me the result?

Cheers, Gerald

**Comment by geraldmwangi** [comment]
and remove 

if(normal.z>=0)

in line 561 of OdmTexturing.cp

**Comment by geraldmwangi** [comment]
I think my angle criterion breaks the visibility criterion on your data, that is the 'best angle' is given to non-visible faces for a particular camera. This is obvious in your data since texture only gets assigned to obsticals like trees, and probably the wrong side of them.
Gerald

**Comment by smathermather** [comment]
Not yet. I was traveling, and I don't think that @dakotabenjamin has had a chance yet, but we're looking forward to trying.

**Comment by dakotabenjamin** [comment]
Looks much better. I'm going to test it on another dataset and I'll give an update on that. 

https://www.dropbox.com/s/plw2506vvczaj8t/odm_texturing-up.zip?dl=0

**Comment by dakotabenjamin** [comment]
@smathermather can probably better tell you about the seneca dataset, and you can check out the images [here](https://github.com/OpenDroneMap/odm_data_seneca) 

Original:
https://www.dropbox.com/s/k6079m0tfhhaaov/odm_texturing_original.zip?dl=0

**Comment by smathermather** [comment]
SfM derived using workflow on the left of this diagram:

**Comment by dakotabenjamin** [comment]
For everyone's reference, here are the differences in texturing on the Seneca dataset:
Current:
o-seneca1
@geraldmwangi 's version: 
g-seneca1

Current:
o-seneca2
@geraldmwangi 's version
g-seneca2

Side-by-side: (left is current, right is @geraldmwangi) 
seneca-side-by-side

I noticed that without proper blending, the results seem less smooth, even if the image assignment is more accurate (note the lines in the side-by-side). If possible, perhaps we should add this as an option until the image blending is improved.

**Comment by smathermather** [comment]
@geraldmwangi -- this dataset was taken on a partially cloudy day, so the image brightness varies a lot between images.  This is derived from dense cloud, but since ODM doesn't yet do any image brightness matching or blending and the input dataset has such high variation in brightness, the combination results in some serious artifacts.

In other words, this is a data problem, not an algorithm problem.

**Comment by smathermather** [comment]
Just checked on a better dataset, and the output looks great.

**Comment by smathermather** [comment]
Ah, I've been thinking optical flow modeling would be a great complement to feature matching, especially since it handles surface types (e.g. smoothly changing surfaces) that feature matching fails on. I think @colek42 is interested in this space too.

**Comment by smathermather** [comment]
Excellent! And good luck with the thesis work.

**Comment by colek42** [comment]
The techniques I have worked with require significant frame overlap, 60 fps
would be desirable,  anything under 30 fps causes tracking to be easily
lost.   The other issue is that the algorithm I have used is not scale
aware,  manual scaling via ground control points would need to be done.
I have some grand plans for this project,  but between my paid work and dad
duties my free time has been scarce.   However,  now that game of thrones
and silicon Valley is over I should have a couple hours a week freed up.

**Comment by smathermather** [comment]
@colek42 -- Could the scale come from feature matching? It seems the techniques become complementary, if this is possible.

**Comment by colek42** [comment]
I think manually overlaying it over imagery from Google or bing and
applying would be the most straight forward way.   There are definitely
some computational methods to do this,  but I   have only read about them
and I don't think it would be on the critical path.

**Comment by smathermather** [comment]
I guess what I mean is ODM already has a couple of ways of turning feature matched point derived meshes (and soon point clouds) into geographic data (using gps ephemeris or GCPs). Why not hook into that for optical flow modeling?

**Comment by colek42** [comment]
I understand, using the existing framework would be the way to go.  I'm
going to make some time to write some code this week.   Has any progress
been made on the python rewrite?

**Comment by smathermather** [comment]
Re: python re-write:
- @JesseCrocker has made it a ways toward a rewrite. I think this is his latest here: https://github.com/JesseCrocker/OpenDroneMap/tree/feature/rewrite-in-python
- @GeospatialDaryl outlined an approach in the wiki:
  - https://github.com/OpenDroneMap/OpenDroneMap/wiki/Z.1-----Run.Pl---1st-Order-Commands-from-Existing-Perl-Driver-Script
  - https://github.com/OpenDroneMap/OpenDroneMap/wiki/Z.2----Core-objOpenDroneMap-Specification

And we should expect some work along these lines by folks at Spotscale on this as well, due in August.

**Comment by smathermather** [comment]
@dakotabenjamin -- I'd be comfortable with merging @geraldmwangi's code in (with appropriate changes as tested above). The problems we are seeing in the Seneca dataset are data issues, not algorithm issues. I'd prefer to have this merged in before we start any texture smoothing work.

**Comment by smathermather** [comment]
I think https://github.com/OpenDroneMap/OpenDroneMap/pull/122 integrates appropriate changes.

**Comment by geraldmwangi** [comment]
Hi guys, thanks for accepting the code. I'll get back to you if/when I
have something with dense reconstruction with optical flow or I need
your help with that.
Regards Gerald

**Comment by smathermather** [comment]
Not at all. Thanks for the contribution Gerald!

**Pull request closed without merging**
