### PR TITLE
Dtm dsm gsd patch

### PR DESCRIPTION
**Pull request by smathermather**
Proposed solution to https://github.com/OpenDroneMap/ODM/issues/914 -- reduce default resolution to 1/16 the resolution of the ortho

### CODE REVIEW

**Comment by pierotofy** [comment]
:+1: this is a good suggestion. I wonder if we should change the default from `5` to `20` instead of adding a multiple: https://github.com/OpenDroneMap/ODM/blob/master/opendm/config.py#L417

The effect would be the same, but the requested units would be consistent with the output raster resolution.

**Comment by smathermather** [comment]
> 👍 this is a good suggestion. I wonder if we should change the default from `5` to `20` instead of adding a multiple: https://github.com/OpenDroneMap/ODM/blob/master/opendm/config.py#L417

Good point, default should also be the same just to make it explicit. What are we doing with docs ATM? Are we keeping them in sync with master or waiting for releases?

**Comment by pierotofy** [comment]
We're trying to keep them in sync with master.

**Comment by pierotofy** [comment]
This line can probably be reverted if the default is now `20`:

```
resolution = gsd.cap_resolution(args.dem_resolution, tree.opensfm_reconstruction, ignore_gsd=args.ignore_gsd) * 4.0
```

Then I think it's good to be merged!

**Comment by smathermather** [comment]
If we’re autocalculating ortho resolution, I think we should autocalculate DEM resolution unless overridden.

**Comment by pierotofy** [comment]
Mm, I'm a bit confused on the last comment. :thinking: 

Orthophoto resolution is defined by the user. Then it's capped to GSD by default (it's not scaled, but if a user asks for 1 cm / pixel resolution, and GSD's maximum is 3 cm / pixel, the resolution is capped at 3 cm / pixel, unless `--ignore-gsd` is passed, in which case the user can choose any resolution without caps).

The same currently happens for DSM/DTM. `gsd.cap_resolution` is the function in charge of doing that.

The higher the resolution, the higher the memory usage. So increasing the default `--demo-resolution` from `5` to `20` will effectively reduce memory usage.

Or are you suggesting adding further modifications?

**Comment by smathermather** [comment]
So, if the orthophoto resolution is 20cm, we would default to the same resolution for the elevation models? It seems, if the orthophoto resolution for a given project is e.g. 20cm due to gsd.cap_resolution, we don't want the same resolution for the elevation models, as they are calculated from the SMVS output scale which is a 4x4 patch. That would result in a noisier elevation model than necessary.

**Comment by pierotofy** [comment]
Thanks for the explanation! If you want to cap the resolution to a multiple of GSD, you can use the `gsd_error_estimate` parameter and write the call as:

```
resolution = gsd.cap_resolution(args.dem_resolution, tree.opensfm_reconstruction, gsd_error_estimate=-3, ignore_gsd=args.ignore_gsd)
```

See `opendm/gsd.py:55` for how that would work.

With that, we can revert the default of dem-resolution to `5`.

**Review by pierotofy — APPROVED** [review]
Looks good to me!

**Pull request merged**
