### PR TITLE
Added Canon PowerShot S100

### PR DESCRIPTION
**Pull request by okiave**
I'm new git so using it from desktop to cloud is a bit confusing.

The above code includes the Canon S100 that I'm going to test.
My work can be verified here: http://www.dpreview.com/products/canon/compacts/canon_s100/specifications
I apologize in advance if I'm making a mess.

thanks!

### CODE REVIEW

**Comment by smathermather** [comment]
Thanks for the pull request!  I'll take a look.

**Comment by okiave** [comment]
I'm going to guess this is resolved because it says closed.
If otherwise, let me know.

@floscher thanks for your help.

**Comment by floscher** [comment]
@okiave no, you have deleted and restored the branch `patch-1`, what closed (disapproved) both pull requests. To approve the changes, you can reopen both pull requests and merge/pull (I don't remember the exact wording of the button) okiave/OpenDroneMap#1.

Once both pull requests have a purple marker saying "Merged" instead of the current red marker saying "Closed", you have succeded. See e.g. #1 for a pull request that was accepted.

I'd recommend the following tutorials to you, which explain how the GitHub Flow and especially pull requests work:
- https://guides.github.com/introduction/flow/
- https://guides.github.com/activities/forking/
- https://www.youtube.com/watch?v=81uKcXZoQ2A

**Comment by smathermather** [comment]
Hi @okiave, I just manually added the powershot s100:
https://github.com/OpenDroneMap/OpenDroneMap/commit/ad266b16c861e0ccc74a031d8e0f2e1dca3e755d#diff-7f13dab363df1ca3ed0607c3d4a6a7bd

Let me know if this is what you intended.

**Comment by okiave** [comment]
@smathermather correct. Thanks for doing it manually.

@floscher thanks for sharing those resources. My future contributions
will be a more fluid experience.

**Comment by smathermather** [comment]
My pleasure, @okiave. Cheers! And welcome to github.

**Pull request closed without merging**
