### PR TITLE
Add logo to bottom of log to make clear ODM is done

### PR DESCRIPTION
**Pull request by smathermather**

### CODE REVIEW

**Review by pierotofy — APPROVED** [review]
+1 for the art!

**Comment by smathermather** [comment]
This is satisfying:
```
[INFO]    Running ODM OrthoPhoto Cell - Finished
[INFO]    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
[INFO]    MMMMMMMdo/-.`.-+yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMmy/-.`.-/odMMMMMMM
[INFO]    MMMMMs.`/shmmdho- /dMMMMMMMMMMMMMMMMMMMMMMMMd: -ohdmmhs/`.yMMMMM
[INFO]    MMMm-`sNMMMMMMMMMd/ oMMMMMMMMMMMMMMMMMMMMMM+ /mMMMMMMMMMNo`-mMMM
[INFO]    MMm..mMMMMMMMMMmhMMs /MMMMMMMMMMMMMMMMMMMM/ yMMhmMMMMMMMMMm..NMM
[INFO]    MM: mMMMMMMMMNo`oMMMo hMMMMMMMMMMMMMMMMMMy oMMMo`oNMMMMMMMMd /MM
[INFO]    MN /MMMMMMMs+.:dMMMMN /MMMMMMMMMMMMMMMMMM: NMMMMd:.+sMMMMMMM: NM
[INFO]    Md +MMMMMMy  .MMMMMMM`-MMMMMMMMMMMMMMMMMM-`MMMMMMM.  yMMMMMM+ mM
[INFO]    MN :MMMMN+`+ymMMMMMMm /MMMMMMMMMMMMMMMMMM/ mMMMMMMmy+`+NMMMM-`NM
[INFO]    MM+ hMMm.:dMMMMMMMMM/ dMMMMMMMMMMMMMMMMMMd /MMMMMMMMMd:.mMMh +MM
[INFO]    MMN-`hMMmMMMMMMMMMN+ sMMMMMMmdhyyyhdNMMMMMo +NMMMMMMMMMmMMy`-NMM
[INFO]    MMMN/`/dMMMMMMMMNy-  ohddy+.``.. .```-+hhy/  -yNMMMMMMMMd/`+NMMM
[INFO]    MMMMMd/.-+syyyo/.-:   ```.- `sN+ hm+ `:`    `/-./oyyys+../dMMMMM
[INFO]    MMMMMMMmho//:/+sdNM+   -yh`.mMM+ hMMy`:mo`  oMNds+/://ohNMMMMMMM
[INFO]    MMMMMMMMMMMMMMMMMMMy   /h.`mMMM+ hMMMs +y-  oMMMMMMMMMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMMMMMMMM/ oh/. `:+os: +so+:  -+h/ yMMMMMMMMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMMMMMMMd /MMM.`hso//. -/+oys oMMN.`NMMMMMMMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMMMMMMM/ mMMN :MMMMMo hMMMMN -MMMy oMMMMMMMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMMMMMMM`.NNNh +NNNNN+ yNNNNN.`NNNd :MMMMMMMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMMMMMMM``---. `-----` .-----  .... -MMMMMMMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMMMMMMM-`dmmy /mmmmm/ ymmmmd``dddy /MMMMMMMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMMMMMMMo hMMN -MMNmm/ ymmNMm :MMM+ yMMMMMMMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMMMMMMMN..NMm. :----` .----- +NMd`-MMMMMMMMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMMMMMMMMh ::.- .hdmm/ ymdds `-./..mMMMMMMMMMMMMMMMMMM
[INFO]    MMMMMMMMMmddddmNMMMM`  om/ sMMM+ hMMN:`hd-  yMMMNmddddmMMMMMMMMM
[INFO]    MMMMMMdo--------:ymy    :s-`sNM+ hMm/ +s.   /ms:--------odMMMMMM
[INFO]    MMMMd:./ydNNMNmdo-.`  `.-..  -s/ so.  ..-.   .-sdmNMNNdy:./dMMMM
[INFO]    MMMy`:dMMMMMMMMMMNy` +mNNNho/-.....-/sdNNmo .yNMMMMMMMMMMd:`yMMM
[INFO]    MMh`/NMm/hMMMMMMMMMd`-NMMMMMMMNmmNNMMMMMMN-.dMMMMMMMMMh/mMN/`hMM
[INFO]    MM.`NMMNo.+mNMMMMMMMy sMMMMMMMMMMMMMMMMMMo yMMMMMMMNm/.sNMMN`-MM
[INFO]    Mm +MMMMMm:`-oMMMMMMM :MMMMMMMMMMMMMMMMMM-`MMMMMMMo-`:mMMMMM/ NM
[INFO]    Mm +MMMMMMm.``hMMMMMM`-MMMMMMMMMMMMMMMMMM-`MMMMMMh``.mMMMMMM+ mM
[INFO]    MM`.MMMMMMMNms./mMMMh oMMMMMMMMMMMMMMMMMM+ dMMMm/.smNMMMMMMM..MM
[INFO]    MMs oMMMMMMMMMm//MMN-.NMMMMMMMMMMMMMMMMMMm`-NMM//mMMMMMMMMMo yMM
[INFO]    MMM+`+NMMMMMMMMMMMd-.dMMMMMMMMMMMMMMMMMMMMh`-dMMMMMMMMMMMN+`oMMM
[INFO]    MMMMy..omNMMMMNNh/`:mMMMMMMMMMMMMMMMMMMMMMMm:`/hNNMMMMNmo..yMMMM
[INFO]    MMMMMNy:.-:///:..+dMMMMMMMMMMMMMMMMMMMMMMMMMMh+..:///:-.:yNMMMMM
[INFO]    MMMMMMMMNdyssyhdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhyssydNMMMMMMMM
[INFO]    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMMMmyoooyNMMMMNsooooshNMMMMMdssdMMMMMmssdMMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMm:  ``` `+NMMm   ``` `/mMMM+  `mMMMM-  +MMMMMMMMMMMM
[INFO]    MMMMMMMMMMMN.  sNMm+  +MMm  /MMms` `mMM/   :MMMo   /MMMMMMMMMMMM
[INFO]    MMMMMMMMMMMy  /MMMMM`  NMm  /MMMMs  +MM: -` yMd `` :MMMMMMMMMMMM
[INFO]    MMMMMMMMMMM+  sMMMMM:  hMm  /MMMMd  -MM- /o `m. h- -MMMMMMMMMMMM
[INFO]    MMMMMMMMMMMo  oMMMMM-  dMm  /MMMMh  :MM- +M- ` +M: .MMMMMMMMMMMM
[INFO]    MMMMMMMMMMMd  .NMMMd  .MMm  /MMMN-  sMM. oMd` -MM/ `MMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMs  .os+` `dMMm  .oo/`  +MMM` oMMmdNMM+  NMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMMd+.```-oNMMMm.````.:omMMMM..yMMMMMMMo..NMMMMMMMMMMM
[INFO]    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
[INFO]    OpenDroneMap app finished - Sun Dec 02 07:41:46  2018
```

**Comment by smathermather** [comment]
@pierotofy -- how does it look on your OS? It looks great on windows Ubuntu install but pretty stretched on Mac. I may adjust a little depending on how it looks elsewhere.

**Comment by pierotofy** [comment]
image

Definitely can't miss it from the screen.

**Comment by smathermather** [comment]
🤣

**Comment by smathermather** [comment]
I can see the end of the process now.

**Comment by smathermather** [comment]
Looks stretched. What's your OS?

**Comment by pierotofy** [comment]
Arch using Terminator. 

image

It's going to be difficult to have a perfect image on all terminals. Depends on the font and there are quite a few.

**Comment by smathermather** [comment]
Oh for sure. Just aiming for some sort of medium. That's a Windows vote for leaving it how it is, and a singular particular config for Linux and Mac for adjusting. How does it look in WebODM? That might be the decider... .

**Comment by pierotofy** [comment]
Probably not as good as the console output window on WebODM is small. But the console output window is going away soon anyway, so I wouldn't use WebODM as a metric.

**Comment by smathermather** [comment]
Ah, yes. It's wide enough but not tall enough.

Fair. Well, for now, I'll leave it as is so that it looks good on my machine. :) I'll probably adjust it later.

**Pull request merged**
