### PR TITLE
UI changes and georeferencing fix

### PR DESCRIPTION
**Pull request by dakotabenjamin**
This PR has two parts. 

### UI changes
In order to simply usage, I've rewritten all the arguments to be simpler. 
```
-h, --help            show this help message and exit
  --images <string>, -i <string>
                        Path to input images
  --project-path <string>
                        Path to the project to process
  --resize-to <integer>
                        resizes images by the largest side
  --start-with <string>, -s <string>
                        Can be one of: resize | opensfm | cmvs | pmvs |
                        odm_meshing | mvs_texturing | odm_georeferencing |
                        odm_orthophoto
  --end-with <string>, -e <string>
                        Can be one of:resize | opensfm | cmvs | pmvs |
                        odm_meshing | mvs_texturing | odm_georeferencing |
                        odm_orthophoto
  --rerun <string>, -r <string>
                        Can be one of:resize | opensfm | cmvs | pmvs |
                        odm_meshing | mvs_texturing | odm_georeferencing |
                        odm_orthophoto
  --rerun-all           force rerun of all tasks
  --rerun-from <string>
                        Can be one of:resize | opensfm | cmvs | pmvs |
                        odm_meshing | mvs_texturing | odm_georeferencing |
                        odm_orthophoto
  --force-focal <positive float>
                        Override the focal length information for the images
  --force-ccd <positive float>
                        Override the ccd width information for the images
  --min-num-features <integer>
                        Minimum number of features to extract per image. More
                        features leads to better results but slower execution.
                        Default: 4000
  --matcher-threshold <percent>
                        Ignore matched keypoints if the two images share less
                        than <float> percent of keypoints. Default: 2.0
  --matcher-ratio <float>
                        Ratio of the distance to the next best matched
                        keypoint. Default: 0.6
  --matcher-neighbors <integer>
                        Number of nearest images to pre-match based on GPS
                        exif data. Set to 0 to skip pre-matching. Neighbors
                        works together with Distance parameter, set both to 0
                        to not use pre-matching. OpenSFM uses both parameters
                        at the same time, Bundler uses only one which has
                        value, prefering the Neighbors parameter. Default: 8
  --matcher-distance <integer>
                        Distance threshold in meters to find pre-matching
                        images based on GPS exif data. Set to 0 to skip pre-
                        matching. Default: 0
  --use-opensfm-pointcloud
                        Use OpenSfM to compute the point cloud instead of PMVS
  --cmvs-maxImages <integer>
                        The maximum number of images per cluster. Default: 500
  --pmvs-level <positive integer>
                        The level in the image pyramid that is used for the
                        computation. see
                        http://www.di.ens.fr/pmvs/documentation.html for more
                        pmvs documentation. Default: 1
  --pmvs-csize < positive integer>
                        Cell size controls the density of
                        reconstructionsDefault: 2
  --pmvs-threshold <float: -1.0 <= x <= 1.0>
                        A patch reconstruction is accepted as a success and
                        kept if its associated photometric consistency measure
                        is above this threshold. Default: 0.7
  --pmvs-wsize <positive integer>
                        pmvs samples wsize x wsize pixel colors from each
                        image to compute photometric consistency score. For
                        example, when wsize=7, x7=49 pixel colors are sampled
                        in each image. Increasing the value leads to more
                        stable reconstructions, but the program becomes
                        slower. Default: 7
  --pmvs-min-images <positive integer>
```

Note that you can now specify images *outside* the project directory, and those files will be copied into the project directory. You can also add GCP files to Docker using the instructions in the README. 

### Georeferencing 
Georeferencing now fails more gracefully. Additionally, when a dataset with no georeferencing (EXIF or GCP) is run, an "ortho"photo is still generated after throwing a bunch of errors. It will probably be unusable but at least the user knows they're using ODM wrong. 
```
[INFO]    Running ODM Georeferencing Cell
[DEBUG]   None
[WARNING] No coordinates file. Generating coordinates file: /project/odm_georeferencing/coords.txt
[WARNING] Could not generate coordinates file. Ignore if there is a GCP file. Error: Error in OdmExtractUtm:
No valid GPS position found
For more detailed information, see log file.

[WARNING] Georeferencing failed. Make sure your photos have geotags in the EXIF or you have provided a GCP file. 
[INFO]    Running ODM Georeferencing Cell - Finished
[INFO]    Running ODM Orthophoto Cell
[DEBUG]   running /code/build/bin/odm_orthophoto -inputFile /project/odm_texturing/odm_textured_model.obj -logFile /project/odm_orthophoto/odm_orthophoto_log.txt -outputFile /project/odm_orthophoto/odm_orthophoto.png -resolution 20.0 -outputCornerFile /project/odm_orthophoto/odm_orthophoto_corners.txt
[WARNING] No coordinates file. A georeferenced raster will not be created
```

Resulting "orthos" will likely be ugly:

odm_orthophoto

### CODE REVIEW

**Comment by dakotabenjamin** [comment]
Looking for someone to test. I've done it with odm_data/langley, odm_data/odm_boruszyn_kap, and tests/test_data with good results.

**Comment by xialang2012** [comment]
great

**Comment by pierotofy** [comment]
Looks good to me! Are you still looking for more tests to be performed? If so, are you looking to just run the default options and see if the output looks reasonable?

**Comment by dakotabenjamin** [comment]
@pierotofy yes please. Specifically for the georeferencing part, I'm looking for expected behavior with more datasets than I've got on hand. *Theoretically* no options are necessary for detecting what type of geotags (exif, gcp) exist.

**Comment by sukoshi1507** [comment]
i have a huge dataset for those interested in testing. would you likenme to share it ?
i was able to process it on a dockerized ODM while setting Docker to use 100% of my ram (16gb).

**Comment by dakotabenjamin** [comment]
Yes please!

**Comment by sukoshi1507** [comment]
will upload soon on box.com and will share the link.

599 pictures / 3.04Gb

**Comment by pierotofy** [comment]
Sorry I haven't had time to test this; I'm updating the opendronemap docker image to the latest master, then I'll update node-opendronemap and I will start testing these new changes.

**Comment by dakotabenjamin** [comment]
I think I merged this too soon. I'm experiencing some errors. I think you can reproduce:
1. Run dataset with EXIF and force quit (^C) during odm_georeferencing
2. Rerun using `--rerun-from odm_georeferencing`

You should get errors like below: 
image


<I'm leaving for the day so I'll test and update tomorrow.>

EDIT: I'm not able to reproduce this

**Comment by pierotofy** [comment]
Just ran this one https://github.com/pierotofy/drone-datasets/tree/master/sand_key_park_clearwater_fl, things are looking good. Point cloud is much more dense.

screenshot from 2017-01-18 21-15-13
screenshot from 2017-01-18 21-16-19

I think the orthophoto offset in respect to google maps is due to the fact that this dataset uses both straight down shots and orbiting shots.

**Comment by pierotofy** [comment]
Here's another dataset, which has much improved results compared to last time I run it, especially the point cloud.

screenshot from 2017-01-18 22-21-56
screenshot from 2017-01-18 22-22-06

**Pull request merged**
