### PR TITLE
Sentera AGX710 tif renaming script and agricultural index

### PR DESCRIPTION
**Pull request by sbonaime**
Geotif created by ODM built from Sentera AGX710 multispectral sensor JPGS doen't have correct band names (ie : 1) RedGreenBlue 2) RedEdgeGarbageNIR 3) No name 4) No name 5) No name 6) No name 7: No name))This script takes a geotif and rename the bands in place.

The agricultural index script cimpute from a multispectral Geotif NDVI, NDRE and GNDVI  index and creates new Geotif rasters for each index

### CODE REVIEW

**Review by pierotofy — APPROVED** [review]
Thanks @sbonaime ! I'm sure this will be useful to others :pray:

**Comment by sbonaime** [comment]
@pierotofy Is this repo https://github.com/OpenDroneMap/multispectral-docs/ the best place to put documentation for Sentera AGX710 multispectral ODM workflow ? Or maybe in https://github.com/OpenDroneMap/docs ?

**Comment by pierotofy** [comment]
> https://github.com/OpenDroneMap/docs

**Comment by sbonaime** [comment]
https://github.com/OpenDroneMap/docs/pull/136

**Pull request merged**
