### PR TITLE
add option to turn off model alignment with sm

### PR DESCRIPTION
**Pull request by smathermather**
Moar untested code! To be tested soon, after the current run finishes or crashes spectacularly. But: if someone wants to review or test while I wait for processing disasters, I would be so obliged.

### CODE REVIEW

**Comment by pierotofy** [comment]
This is why I love open source.

image

**Comment by smathermather** [comment]
https://github.com/OpenDroneMap/ODM/issues/1048

**Comment by pierotofy** [comment]
Any updates on this one?

**Comment by pierotofy** [comment]
Implemented via https://github.com/OpenDroneMap/ODM/pull/1544/commits/4c59bb7c5c8a55d947bf2559dbbe2f350f259a7c

Thanks for the draft!

**Pull request closed without merging**
