### PR TITLE
ODM: installation improvements

### PR DESCRIPTION
**Pull request by cezio**
This is WiP, contains fixes for #109:
- add options to install.sh script (custom build dir, custom install dir, ability to skip system packages install and cleaning build dir)
- improvements in `install.sh` (parametrize of make call, use headers/libs installed system-wide instead of local copies, updated dependencies, patch for cmvs instead of full source archive)
- adjusting paths in `run.pl`, use of env variables to locate binaries and libraries
- fix broken cmvs `base/numeric/mylapack.h/cc`: signature didn't match header file (https://github.com/OpenDroneMap/OpenDroneMap/pull/110/files#diff-08694398d092944a0fe84fc0b2477895R154 and https://github.com/OpenDroneMap/OpenDroneMap/pull/110/files#diff-08694398d092944a0fe84fc0b2477895R167), removed `<clapack/f2c.h>` include (wrong path, `f2c.h` already included by `clapack.h`)

### CODE REVIEW

**Comment by smathermather** [comment]
Testing now.

**Comment by smathermather** [comment]
So far it's failing on pmvs, not sure what I'm doing wrong:

`./install.sh -d /usr/local/ -i`

```
...
g++ -c -O2 -Wall -Wno-deprecated -I/usr/local/include -I/usr/local/include ../base/pmvs/seed.cc
g++ -c -O2 -Wall -Wno-deprecated -I/usr/local/include -I/usr/local/include ../base/numeric/mylapack.cc
../base/numeric/mylapack.cc:6:29: fatal error: clapack/clapack.h: No such file or directory
 #include <clapack/clapack.h>
                             ^
compilation terminated.
make: *** [mylapack.o] Error 1
make: *** Waiting for unfinished jobs....
Error during building cmvs/pmvs
```

**Comment by cezio** [comment]
https://github.com/OpenDroneMap/OpenDroneMap/pull/110#issuecomment-102657485

Yep, seems my bad. I'm not using Ubuntu, so couldn't check this. Will add proper packages to installation  list and test with a VM.

**Comment by smathermather** [comment]
Cool.

**Comment by dbaldwin** [comment]
Great. If I can help test on Ubuntu please let me know. I do all my processing on Ubuntu so I'll be glad to test.

**Comment by smathermather** [comment]
Hi @cezio -- definitely interested in integrating this. Do you want me to dig in and debug, or do you have time to check this?

Really appreciate the contribution.

**Comment by cezio** [comment]
Yes, I want to finish this one, although I don't have time to do it now. I hope to get back to this in about 1-2 weeks.

**Comment by smathermather** [comment]
Awesome. Really appreciate it @cezio.

**Comment by dakotabenjamin** [comment]
This is a pretty stale PR. I'm going to close this. If you have improvements to add from here, see the `edgarriba-cmake` branch first and see if that code hasn't already done it or makes the improvements obsolete.

**Pull request closed without merging**
