### PR TITLE
--skip-resize flag and writing final transform in extra file, so data from reconstruction.json can be transformed into georeferenced space

### PR DESCRIPTION
**Pull request by fredlllll**
adding a --skip-resize flag, so instead of having to figure out the size of a picture and then passing that to --resize-to, the images just get copied, which saves us the work of encoding the images again, even if size didnt change

### CODE REVIEW

**Review by pierotofy — APPROVED** [review]
Looks good to me!

**Comment by dakotabenjamin** [comment]
I'm running into this error: 
```
[DEBUG]   Resizing dataset to: /home/dmb2/opendronemap/tests/test_data/images_resize
Traceback (most recent call last):
  File "/home/dmb2/opendronemap/run.py", line 46, in <module>
    plasm.execute(niter=1)
  File "/home/dmb2/opendronemap/scripts/resize.py", line 131, in process
    if params.skip_resize:
NameError: global name 'params' is not defined
```

**Comment by dakotabenjamin** [comment]
needs to be `self.params.skip_resize`

**Comment by dakotabenjamin** [comment]
Can you describe the changes being made to georef.cpp?

**Comment by fredlllll** [comment]
darn that wasnt supposed to go into this pullrequest D: it should basically output the final transform in an extra file, not just in the log. i just wanted to test it, but also ran into the error with opencv missing (see gitter). dont know if that is cause of my changes, or cause of something else

fixed the missing self.

**Comment by dakotabenjamin** [comment]
No worries, in the future you can checkout a new branch and work on it so you don't affect `master`

**Comment by fredlllll** [comment]
ok after running configure.sh a second time it found opencv miraculously and the georef.cpp compiled

**Pull request merged**
