### PR TITLE
Add option to use OpenSfM to compute the point cloud

### PR DESCRIPTION
**Pull request by paulinus**
OpenSfM has now a command to compute depth maps and merge them into a point cloud.  This PR adds an the `--use-opensfm-pointcloud` option to ODM to use such command instead of PMVS.

### CODE REVIEW

**Comment by smathermather** [comment]
(If we like it enough, it should default to the OpenSfM point cloud, and need a flag for using PMVS...) :)

**Comment by dakotabenjamin** [comment]
It's taking about 2 - 2.5 minutes per depth map on a 16 core/44GB server. Is this what I should be expecting for costs?

This is on the Aukerman data, resized to 2400 (default).

**Comment by dakotabenjamin** [comment]
First run went great. It's (understandably) slow, but despite that I'm excited for these changes. Some questions:
1. I've noticed substantial noise in the merged.ply point cloud. It doesn't seem to carry into the mesh, but is this expected?
2. odm-3 is a release from the most recent commit. Are there any other significant differences between odm-2 and odm-3 that we should be made aware of?

**Comment by theincorrect** [comment]
Yesterday It took all day to process a set of 348 images on VM with Ubuntu.
Specs of machine:
- 4 cores
- 32 GB RAM
- 120 GB HDD

Texturing failed with error:

```
[INFO]    Running MVS Texturing Cell
[DEBUG]   Writing MVS Textured file in: /home/kg.ru/kornev/field38undist/odm_texturing/odm_textured_model.obj
[DEBUG]   running /home/kg.ru/kornev/odm/SuperBuild/install/bin/texrecon /home/kg.ru/kornev/field38undist/opensfm/reconstruction.nvm /home/kg.ru/kornev/field38undist/odm_meshing/odm_mesh.ply /home/kg.ru/kornev/field38undist/odm_texturing/odm_textured_model -d gmi -o none
/home/kg.ru/kornev/odm/SuperBuild/install/bin/texrecon (built on Oct  5 2016, 11:08:29)
Load and prepare mesh:
PLY Loader: comment PCL generated
Reading PLY: 93104 verts... 186057 faces... done.
Warning: Zero-length normals detected: 40 face normals, 0 vertex normals
Generating texture views:
NVM: Loading file...
NVM: Number of views: 338
NVM: Number of features: 0
        Loading 0%...terminate called recursively
Aborted
[ERROR]   quitting cause:
        /home/kg.ru/kornev/odm/SuperBuild/install/bin/texrecon /home/kg.ru/kornev/field38undist/opensfm/reconstruction.nvm /home/kg.ru/kornev/field38undist/odm_meshing/odm_mesh.ply /home/kg.ru/kornev/field38undist/odm_texturing/odm_textured_model -d gmi -o none
returned with code 34304.

An error occurred. Check stdout above or the logs.
```

**Comment by theincorrect** [comment]
I guess OpenSFM's depth maps are now computed in a single thread. Am I right?

**Comment by theincorrect** [comment]
Rerun from texturing did not helped.

```
[INFO]    Running MVS Texturing Cell
[DEBUG]   Writing MVS Textured file in: /home/kg.ru/kornev/field38undist/odm_texturing/odm_textured_model.obj
[DEBUG]   running /home/kg.ru/kornev/odm/SuperBuild/install/bin/texrecon /home/kg.ru/kornev/field38undist/opensfm/reconstruction.nvm /home/kg.ru/kornev/field38undist/odm_meshing/odm_mesh.ply /home/kg.ru/kornev/field38undist/odm_texturing/odm_textured_model -d gmi -o none
/home/kg.ru/kornev/odm/SuperBuild/install/bin/texrecon (built on Oct  5 2016, 11:08:29)
Load and prepare mesh:
PLY Loader: comment PCL generated
Reading PLY: 93104 verts... 186057 faces... done.
Warning: Zero-length normals detected: 40 face normals, 0 vertex normals
Generating texture views:
NVM: Loading file...
NVM: Number of views: 338
NVM: Number of features: 0
        Loading 0%...terminate called after throwing an instance of 'util::Exception'
  what():  Cannot determine image format
Aborted
[ERROR]   quitting cause:
        /home/kg.ru/kornev/odm/SuperBuild/install/bin/texrecon /home/kg.ru/kornev/field38undist/opensfm/reconstruction.nvm /home/kg.ru/kornev/field38undist/odm_meshing/odm_mesh.ply /home/kg.ru/kornev/field38undist/odm_texturing/odm_textured_model -d gmi -o none
returned with code 34304.

An error occurred. Check stdout above or the logs.
```

**Comment by triceam** [comment]
I am seeing similar behavior.  24 core machine, but only one CPU pegged at 100%, the rest are idle.

**Comment by smathermather** [comment]
This is awesome. The quality increase is unprecedented. @paulinus -- is there any plan to parallelize this?

**Pull request merged**
