### PR TITLE
Make euclidean merge available in contrib directory

### PR DESCRIPTION
**Pull request by smathermather**
An attempt to expose the euclidean merge that so helpfully is part of split merge to merge other, similarly formatted elevation models, say one from MERIT Hydro and another from OpenDroneMap.

### CODE REVIEW

**Comment by smathermather** [comment]
~~There's something I'm doing wrong here, I could use a hint. I'm unclear if it's the format of my inputs tifs or something subtler.~~

Got it. Had a path issue on output.

```
docker run -ti --rm -v /home/sillyuser/merging:/input --entrypoint /code/contrib/dem-blend/dem-blend.py dem_blend /input
[INFO]    Computing euclidean distance: /input/merit.euclideand.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
[INFO]    Computing euclidean distance: /input/dsm.euclideand.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
[INFO]    2 valid DEM rasters to merge
[INFO]    Output bounds: 642157.3721 8321070.3609 660157.3721 8331420.3609
[INFO]    Output width: 9000, height: 5175
[INFO]    Adjusted bounds: 642157.3721 8321070.3609 660157.3721 8331420.3609
(base) sillyuser@crankier:~/merging$ ls
dsm.euclideand.tif  dsm.tif  merit.euclideand.tif  merit.tif
```

**Comment by smathermather** [comment]
Looks like once possible issue with general use is null values are hard coded:
https://github.com/OpenDroneMap/ODM/blob/master/opendm/dem/commands.py#L203C14-L203C19

**Comment by smathermather** [comment]
What I haven't looked at is the multiprocessing side of this. I don't even know if the dem merge step supports multiprocessing, so that's a bit of dangling import that needs resolved. Otherwise: ready for review.

**Comment by pierotofy** [comment]
:+1:

**Pull request merged**
