### PR TITLE
Native Windows Support

### PR DESCRIPTION
**Pull request by pierotofy**
This PR adds the necessary changes to bring full native support on Windows (no docker, no WSL!).

image

Still to do:

 - [x] Documentation for building, usage notes in README
 - [x] Automated packaging / release using Github CI. Not sure how code signing can be handled, need to do some research
 - [x] Exhaustive testing on Windows
 - [x] Exhaustive testing on Linux / Docker to make sure nothing broke there :hammer: 

A beta setup installer can be downloaded from https://drive.google.com/file/d/1vxYhHYfniIVORexV536zvFxdjF8UkkpT/view?usp=sharing (I'd welcome help testing this, report any issues you find here on GitHub? :pray: )

This was long overdue and it's going to greatly facilitate adoption of ODM on Windows. :clinking_glasses:

### CODE REVIEW

**Comment by pierotofy** [comment]
Passes oats test suite.

**Comment by Miner-Jeff** [comment]
Hi Piero,
Has the Beta setup installer been updated with to accomodate spaces in folder path?
It appears that the number remains 2.5.0.
I downloaded 2.5.0 again and installed it in the same location as previoulsy C:\ODM
I still get an error when trying to process a dataset with spaces in the path.

I will have to google how to download & install a Github repository to my PC. If the Beta installer isn't updated.

Cheers & Thanks!
Jeff

**Comment by pierotofy** [comment]
Should be; try to uninstall and re-install it? (Completely remove the C:\ODM folder). Version number should be the same.

**Comment by Miner-Jeff** [comment]
Okay,
I installed ODM 2.5.0 using the beta installer.
Tried running ODM on a dataset.
It failed rather quickly after starting.

I used the Windows uninstaller to uninstall ODM.
I installed ODM 2.5.0 using the beta installer again.
Tried running ODM on the same dataset.
It failed rather quickly after starting.

I uninstalled ODM using the Windows uninstaller, then deleted all the ODM folders present in the project folder.
Reinstalled ODM using the beta installer.
Attempted to process the same dataset again (272 images.)
It has failed again, however it seemed to take longer for the failure to occur.
I have attached a .txt file with what I could highlight and copy from the console window. Rather than clutter the message box.
[ODM Fail 2021-05-17 03.txt](https://github.com/OpenDroneMap/ODM/files/6496877/ODM.Fail.2021-05-17.03.txt)

Please advise wheat my next steps should be or what additional information I can provide.

Cheers,
Jeff

**Comment by pierotofy** [comment]
Thanks @Miner-Jeff !

Looks like this was a different issue, caused by leaky file descriptors. I've made a fix for it in https://github.com/simonfuhrmann/mve/pull/545

I've also improved the installation/uninstallation process. Re-running the setup should be all you need to continue processing the dataset (and perhaps complete it successfully this time!)

**Comment by bowman813** [comment]
Hi and thanks for this Windows version without Docker and WSL2.

I downloaded and installed the last version today.

I have a geo.txt file with RTK/PPK modified coordinates in my images folder, I can use it with WebODM without any problem after finding the good syntax for this file.

But with native Windows ODM 2.5.0, this file seems to be not used, only EXIFs from pics are considered.
So I tried with "--geo E:\odm\profil3\images" argument, but I always have this error:
_[INFO]    Found image geolocation file
Traceback (most recent call last):
  File "C:\ODM\\run.py", line 68, in <module>
    retcode = app.execute()
  File "C:\ODM\stages\odm_app.py", line 83, in execute
    self.first_stage.run()
  File "C:\ODM\opendm\types.py", line 319, in run
    self.process(self.args, outputs)
  File "C:\ODM\stages\dataset.py", line 121, in process
    gf = GeoFile(tree.odm_geo_file)
  File "C:\ODM\opendm\geo.py", line 12, in __init__
    with open(self.geo_path, 'r') as f:
PermissionError: [Errno 13] Permission denied: 'E:\\odm\\profil3\\images'_

I did not find any solution for this problem or direct use of the geo.txt file without the --geo option.
Many thanks in advance!
Denis

**Comment by pierotofy** [comment]
You need to pass the full path to the geo file. E.g. `--geo E:\odm\profil3\images\geo.txt`

**Comment by bowman813** [comment]
It perfectly works, thanks Piero!

**Comment by pierotofy** [comment]
CI working, need to update README, then we can merge and release.

**Comment by pierotofy** [comment]
This is working well enough to be released. No apparent regressions from testing on docker/linux.

Probably some quirks still to fix, but no reason to wait.

**Pull request merged**
