### PR TITLE
proj4 fixes, numpy fixes, and others

### LINKED ISSUE #935: Automagical UTM south zone detection would be nice to have
ODM always writes out UTM coordinates for northern hemisphere zones in the georeferencing step.

usage:
`time docker run -ti --rm -v $(pwd):/datasets/code opendronemap/opendronemap --project-path /datasets --end-with odm_georeferencing --rerun-all --force-ccd 5.97 --time`

sample image EXIF: 
```
exiftool image.jpg
....
GPS Altitude                    : 624.5 m Above Sea Level
GPS Latitude                    : 35 deg 18' 48.69" S
GPS Latitude Ref                : South
GPS Longitude                   : 149 deg 3' 13.25" E
GPS Longitude Ref               : East
GPS Position                    : 35 deg 18' 48.69" S, 149 deg 3' 13.25" E
...
```
ODM writes out the proj string:
`+units=m +no_defs=True +datum=WGS84 +proj=utm +zone=55 ` 

...to `odm_georeferencing`, which needs `+south`.

PDAL medatata output:
```
pdal info --metadata odm_georeferencing/odm_georeferenced_model.laz | jq .metadata.srs.wkt
"PROJCS[\"WGS 84 / UTM zone 55N\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",147],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],AUTHORITY[\"EPSG\",\"32655\"]]"
```

..should be `EPSG:32755` (UTM 55 South)

I should dive in and fix it myself, but lack time right now :/ sorry. Test image sets: 

https://drive.google.com/open?id=1iKaln4zzi7lnvn4Ced8Y7clr9gwe4u9w

Theres a .7z file which has 'overhead' imagery, the other data (backyard-test) is oblique. Either way, both get northified. I've also tested on third-party provided imagery and found the same issue (completely different collection platform).

(the ODM command above will have the correct ccd width for the imagery here)

Cheers

### PR DESCRIPTION
**Pull request by pierotofy**
Fixes #935 

@adamsteer could you verify that this fixed the problem for your dataset?

### CODE REVIEW

**Comment by pierotofy** [comment]
Fixes #885 and https://community.opendronemap.org/t/attributeerror-nonetype-object-has-no-attribute-projection/1667/2

**Comment by pierotofy** [comment]
Will merge this in 2 days unless there are objections.

**Comment by adamsteer** [comment]
Go for it, I won’t have time to test in the next two days unfortunately. IMO the sooner the projection fix makes it into docker builds the better.

**Comment by smathermather** [comment]
Merp.

```
Traceback (most recent call last):
  File "/home/useruser/ODM/run.py", line 11, in <module>
    from scripts.odm_app import ODMApp
  File "/home/useruser/ODM/scripts/odm_app.py", line 5, in <module>
    from opendm import types
  File "/home/useruser/ODM/opendm/types.py", line 5, in <module>
    from opensfm.exif import sensor_string
ImportError: No module named opensfm.exif
```

**Comment by pierotofy** [comment]
I just ran your dataset and `pdal info` returned the following `wkt`:

```
"wkt": "PROJCS[\"WGS 84 \/ UTM zone 55S\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",147],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",10000000],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],AUTHORITY[\"EPSG\",\"32755\"]]"
```

So I think it should be OK.

**Comment by pierotofy** [comment]
@smathermather is that from a clean clone?

**Comment by smathermather** [comment]
Yes, but as I have been doing this distracted with family members jumping on my head, I did not checkout the branch, just cloned your repo and ran on master... . Standby.

**Comment by pierotofy** [comment]
https://github.com/numpy/numpy/pull/12754 has been merged upstream, but it might be a few weeks before it's released as a pip package.

**Comment by smathermather** [comment]
It runs it runs!

**Review by smathermather — APPROVED** [review]
Looks good. I'll pull these changes into the mve branch and see where that gets us!

**Comment by smathermather** [comment]
🥇

**Comment by cioffij** [comment]
Please forgive my ignorance of git.  I installed WebODM today, clone the repo today.  Should I expect that this fix is included?  I am getting the exact same error.

**Comment by cioffij** [comment]
I seem to be up to date.
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
```
nothing to commit, working directory clean

**Comment by smathermather** [comment]
The WebODM repo may be up to date, but it usually takes a few days for the build process for the docker machines to catch up.

**Comment by pierotofy** [comment]
@cioffij did you issue ./webodm.sh update?

**Comment by cioffij** [comment]
I had not done that.  Thanks.  That seems to have worked.
The Lightning cloud servers need to be updated to, I guess.  :-)

Thanks much.

**Comment by adamsteer** [comment]
I *just* got around to testing this - I’m correctly getting UTM south zones now. thanks!

**Pull request merged**
