### PR TITLE
Tweaks to run.py

### PR DESCRIPTION
**Pull request by lupus78**
This improves the code quality and output of run.py.
- 2 new functions print_task_header(), print_task_info(), which are printing the task messages simiallary. (We may add colors later for more readabilty)
- tweaked the run() function to only print the command if error happens, cleans up the output!
- using mkdir_p() everywhere, there we many folder created without it...
- turned the --zip-results argument into a last task. I think it's nicer like this.
- prepare_objects() optimize, got a bit faster, removed redundant and unused code bits
- tweaked the messages of what is happening right now

### CODE REVIEW

**Comment by lupus78** [comment]
pls note! this PR also contains the "XYZ point cloud output" commit, which I have submitted in #222

**Comment by lupus78** [comment]
I have just pushed Object Oriented tweaks to this PR.

There are two Classes
ODMJob: this is the main class, initiated with the job folder, and each task is a method of the class
ODMPhoto: this is for the image, stores the exif infos, and makes the resizes, and other photo related stuff

I have based it on the #175, but this one applies it to the whole run.py.

**Comment by dakotabenjamin** [comment]
Hey @lupus78 you should check out @edgarriba 's fork: https://github.com/edgarriba/OpenDroneMap/tree/cmake

The fork contains some massive changes to the code structure, including OO-ification. I don't mind merging this branch with the new classes, but just know that in the future those changes will be overwritten.

**Comment by lupus78** [comment]
Hm... I didn't know about this fork.... should have save me some work. When will @edgarriba 's fork be merged?

**Comment by dakotabenjamin** [comment]
We're working on testing now. Because of the large rework of the code structure it could take some time

**Pull request closed without merging**
