### PR TITLE
Add extra report file op, disable snap builds

### PR DESCRIPTION
**Pull request by pierotofy**
Discussion on report issue: https://community.opendronemap.org/t/permission-denied-wont-write-report/17891

- Also disables Snap builds: https://community.opendronemap.org/t/how-many-people-use-snapcraft/17788

### CODE REVIEW

**Comment by pierotofy** [comment]
Related: #1709

**Comment by pierotofy** [comment]
* Removes WSL/WSL2 commands/instructions, which have been broken for years also. These were from a time before we had native Windows support.

**Comment by John-Nagle** [comment]
Nobody used the snap version because the documentation didn't mention it prominently. It's easy to install. No need for docker. No need for admin access. Works fine on current Ubuntu. I'd like to have the snap version back.

**Comment by smathermather** [comment]
@John-Nagle -- we need someone to take on the snap build for it to continue. We don't currently have a maintainer who can fix it when it periodically breaks, and we require that in order to maintain it as a build.

**Pull request merged**
