### PR TITLE
Upgrade to Docker 16.04, typo fix in docker build command

### PR DESCRIPTION
**Pull request by smathermather**

### CODE REVIEW

**Comment by pierotofy** [comment]
6ae5a93e8852 is a very specific PDAL image. I'm assuming we want to freeze at a particular release to avoid compilation problems?

**Comment by smathermather** [comment]
That was the idea, although probably unnecessarily specific.

**Comment by dakotabenjamin** [comment]
@smathermather are we holding on this?

**Comment by smathermather** [comment]
Yup. I think bringing in all of PDAL is overkill. We should be more selective.

**Comment by smathermather** [comment]
Closing in favor of https://github.com/OpenDroneMap/OpenDroneMap/pull/470/commits/e06f24877cad27af71333b6ff740ef67e256bf2d

We'll need a separate pull request for the docker image upgrades similar to this diff:
https://github.com/OpenDroneMap/OpenDroneMap/pull/470/commits/e06f24877cad27af71333b6ff740ef67e256bf2d

**Pull request closed without merging**
