### PR TITLE
Edge Swaps for substantially improved building corners

### PR DESCRIPTION
**Pull request by pierotofy**
Adds a new edge swap meshing refinement mechanism (now part of `dem2mesh`) which substantially improves the rendering quality of building corners in orthophotos.

### CODE REVIEW

**Comment by pierotofy** [comment]
image

image

**Comment by pierotofy** [comment]
image


image

**Comment by pierotofy** [comment]
image

image

**Comment by pierotofy** [comment]
image

image

**Comment by pierotofy** [comment]
image

image

**Comment by Miner-Jeff** [comment]
Hello @pierotofy will this pushed/ported to the Native windows installer? I believe it sits at version 2.7.1 of Jan 13, 2022.

Keep up the amazing work!

Cheers!

**Comment by pierotofy** [comment]
Yesss, update coming soon!

**Pull request merged**
