### PR TITLE
Pseudo-georeferencing for datasets missing GPS/GCP information, AKA putting bananas on the map

### PR DESCRIPTION
**Pull request by pierotofy**
Often times people use ODM to process non-georeferenced datasets. In these cases georeferencing is not expected, but people still expect an orthophoto (and DEMs)!

This PR addresses that.

image

image

### CODE REVIEW

**Comment by pierotofy** [comment]
Should also fix #1065 @smathermather

**Comment by smathermather** [comment]
Uhh, flipping spectacular.

**Comment by pierotofy** [comment]
Let's not forget about banana health visualized directly in WebODM.

image

**Comment by smathermather** [comment]
I would value that analysis at $120k.

**Comment by smathermather** [comment]
Totally dig the health index of the banana sticker.

**Comment by smathermather** [comment]
Quick and dirty orthophoto (in NIR/G/B) of my dining room table:

image

Elevation model of violets on dining room table
image

**Review by smathermather — APPROVED** [review]
Amazing. That will save me a lot of effort with these small unreferenced models and reduce a lot of confusion for new users.

**Pull request merged**
