### PR TITLE
convert ccd_defs.pl to json. Because it's data, not code.

### PR DESCRIPTION
**Pull request by JesseCrocker**
This also seems like a necessary step if #20 is going to happen

### CODE REVIEW

**Comment by smathermather** [comment]
Awesome and looks good. What have you tested it on?

**Comment by smathermather** [comment]
@JesseCrocker -- testing now...

**Comment by smathermather** [comment]
@JesseCrocker -- what have you tested this on? Struggling to get to work, but I haven't had any time to do a deep dive on why.

**Comment by smathermather** [comment]
Ok, here's the error I get when attempting to use:

vagrant@vagrant-ubuntu-trusty-64:~/odm_data/caliterra$ ~/OpenDroneMap/./run.pl
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC
 contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /us
r/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/
lib/site_perl .) at /home/vagrant/OpenDroneMap/./run.pl line 14.
BEGIN failed--compilation aborted at /home/vagrant/OpenDroneMap/./run.pl line 14
.

**Comment by smathermather** [comment]
Add libswitch-perl a la:

https://github.com/OpenDroneMap/OpenDroneMap/tree/convert-ccd_defs.pl-to-json

**Comment by bgirardot** [comment]
According the compare with that branch, libjson is added twice in 14.04 part of install.sh

**Comment by smathermather** [comment]
Whoops! Fixed.

**Comment by JesseCrocker** [comment]
I didn't do extensive testing on this. I tested it on a couple of the sample data sets and made sure it got the right value, but didn't let it go all the way through the processing after that. I'll take another look at it.

**Comment by smathermather** [comment]
Thanks!

**Comment by bgirardot** [comment]
Hi all. That missing Switch perl lib has been there since I first downloaded the software, it is not specific to this patch if that matters at all.

I'll give the patch a test in the vagrant environment as well.

**Comment by smathermather** [comment]
Thanks. Will fix in the main branch too then.

**Comment by smathermather** [comment]
Ok, fixed in the main branch:
https://github.com/OpenDroneMap/OpenDroneMap/commit/37e4b1835b8f0acf637d56b6cf66950b244705f6

**Comment by bgirardot** [comment]
this pr runs fine in the vagrant precise32 environment.

**Comment by smathermather** [comment]
Will merge then...

**Pull request merged**
