### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by xxfelixxx**
Added pre-commit hook and script to check that ccd_defs.json compiles.

Add a symlink from hooks/pre-commit to .git/hooks/pre-commit
to enable it.

### CODE REVIEW

**Comment by smathermather** [comment]
Awesome! Will try later this week.

**Comment by dakotabenjamin** [comment]
@xxfelixxx I've never used pre-commit hooks before. If we pull this as-is, would we also need to suggest future PRs that update ccd_defs.json enable this before submitting, or would this hook permanently affect the repository?

**Comment by xxfelixxx** [comment]
The hook has to be enabled by creating a link to the .git/hooks directory.
The link does not get added to the repo.  It can be disabled in the future
by removing the link.

You would need to ask people to enable this before making changes to
ccd_defs, keeping it optional for them, but the maintainers of this repo
should have it enabled for evaluating pull requests.

Felix

**Comment by dakotabenjamin** [comment]
@smathermather I don't think there's any harm in merging this PR. @xxfelixxx can you fix ccd_defs.json and update the readme before we merge?

**Comment by xxfelixxx** [comment]
Merged latest upstream, updated README.md and fixed ccd_def.json.

Thanks,

Felix

**Pull request merged**
