### PR TITLE
Revert "Upgrade Bundler + add support for Ceres solver"

### PR DESCRIPTION
**Pull request by smathermather**
Reverts OpenDroneMap/OpenDroneMap#123

We seem to have issues with matching since the change to Ceres solver. I am going to revert this now in advance of more testing and refinement.

cc @chris-cooper

### CODE REVIEW

**Comment by smathermather** [comment]
@dakotabenjamin -- can you review and test this revert?

**Comment by chris-cooper** [comment]
OK no worries.  Sorry I don't have the bandwidth to look into the issues atm.

**Comment by smathermather** [comment]
Cool @chris-cooper. Love the speed improvements. Hopefully I'll have some more bandwidth soon myself.

**Comment by smathermather** [comment]
At first blush, https://github.com/OpenDroneMap/OpenDroneMap/issues/147 might be related.

**Comment by dakotabenjamin** [comment]
The likely explanation to the recent bundle of errors is the switch from using bundler version 0.4 (from 2010) to the git submodule, a huge jump in terms of updated code. I think it is unwise to use another repo's git submodules (see @chris-cooper 's advice in #123, which we aptly ignored). After this revert, let's fork ceres and bundler_sfm and apply these changes to a development branch to continue testing. Or move over to [OpenSFM](https://github.com/mapillary/OpenSfM), which integrates Ceres already.

**Comment by dakotabenjamin** [comment]
I haven't found any problems with this PR.

**Pull request merged**
