### PR TITLE
Fix GitHub Actions

### LINKED ISSUE #1185: Fix GitHub Actions
Currently the GitHub actions are broken.

### PR DESCRIPTION
**Pull request by lucyllewy**
I've tested these actually work on my fork, so these should be good to go.

fixes #1185

### CODE REVIEW

**Comment by diddledan** [comment]
fixes #1185

**Comment by pierotofy** [comment]
Fantastic! Thanks!

**Comment by Saijin-Naib** [comment]
Will the WSL images be rebuilt when the SNAP packages get built/updated with each PR merged?

**Comment by lucyllewy** [comment]
They should be built in parallel - there's a separate workflow for the docker/wsl build and the snapcraft build

both workflows are set to build on new tags being created for releases, and the snapcraft build has an extra configuration to build every commit added to master and put that in the store's `edge` channel.

**Pull request merged**
