### PR TITLE
PDAL 1.4 and GDAL 2.1.0 update

### PR DESCRIPTION
**Pull request by smathermather**
This pulls the latest 1.4 PDAL in preparation for a variety of point filtering and digital terrain model improvements.

Oh ya, and GDAL 2.1.0 and multithreaded gdal_translate FTW.

### CODE REVIEW

**Comment by smathermather** [comment]
And can I say, gdal_translate on my 20 core machine is v. fast now.

**Comment by dakotabenjamin** [comment]
Once you add the Dockerfile update, I will merge.

**Comment by smathermather** [comment]
Done.

**Review by dakotabenjamin — APPROVED** [review]
For the Dockerfile I'd say keep it to one line but I'm working on a Dockerfile minimization anyways so it can get worked into that.

**Pull request merged**
