### PR TITLE
Multispectral improvements [WIP]

### PR DESCRIPTION
**Pull request by pierotofy**
Improves multispectral calibration / processing.

TODO:
 - [ ] Improve parameter passing (JSON file instead of multiple command line parameters)
 - [ ] Testing

### CODE REVIEW

**Comment by ckato3** [comment]
Piero, Sorry for the delay in replying.

I'm currently in the process of measuring NDVI maps of "Japanese sake rice" using two different types of drones (Parrot Sequoia, and DJI P4 Multispectral).

At the same time, in order to ensure the accuracy of NDVI values, we are examining the model function that relates the subject reflectance and photo-image intensity, and determining the camera specific parameters.

In determining the model function and the parameters, we are using spectral reflectance measurement instruments, which is traceable to international primary standards.

We are working on improving our developing python codes, and will upload it as soon as it is completed.

ckato3

**Comment by pierotofy** [comment]
Hey @ckato3 :hand: thanks for the update! No need to apologize. 

Look forward to see your improvements!

**Comment by pierotofy** [comment]
I'll close this for now; feel free to re-open once this is ready. :pray:

**Comment by ckato3** [comment]
There are numerous additions and modifications I have made to the ODM source code, so I will take it step-by-step and submit pull requests starting with the easiest ones.

**Pull request closed without merging**
