### PR TITLE
Update reference image

### PR DESCRIPTION
**Pull request by smathermather**

### CODE REVIEW

**Comment by smathermather** [comment]
I don't know why Atom decided to change all those durn spaces.

**Comment by pierotofy** [comment]
That's a really nice DSM!

**Comment by smathermather** [comment]
Yeah, imagery via Federico Debetto - KMedia SAS. It's Stone Town's Fort and the Sultan's Palace / Beit-al-Ajaib. He's offered it as a research dataset, so expect to see it soon in with the test datasets.

**Comment by smathermather** [comment]
I mean, this is awefully purdy:
image

**Pull request merged**
