### PR TITLE
Multispectral improvements 211224_

### PR DESCRIPTION
**Pull request by ckato3**
This version supports multispectral photography with the Parrot SEQUOIA camera and DJI P4 Multispectral.

A number of optional parameters can be specified ( 12 for SEQUOIA, 5 for P4 Multispectral), but in most cases you should be able to get a mostly satisfactory NDVI image without specifying these optional parameters.

If the optional parameters are determined using images taken with a standard reflector, it will be possible to compensate for individual camera differences and improve the accuracy of the reflectance for each spectral band, and NDVI images.

### CODE REVIEW

**Comment by ckato3** [comment]
To distinguish it from the branch "multispec" by pierotofy (primitive version by ckato3), this PullRequest is done in branch "multispectral".

**Comment by sbonaime** [comment]
@ckato3 Hi,

Do you think this branch could be used with a Sentera AGX710 ? For each shot, this sensor creates two JPGS (RedEdge, Garbage, NIR ands Red, Green, Blue bands) taken at slightly different time. It is not possible to created a TIFF

Maybe it is possible to add this sensor ?

**Comment by ckato3** [comment]
The code I added for the multispectral calculation only works if the camera is a Parrot Sequoia or a DJI P4 Multispectral.
Therefore, for images taken with cameras other than these two models, the control is passed to the original OpenDroneMap, and the results will be exactly the same as the original ODM.

**Comment by Saijin-Naib** [comment]
@ckato3 , thanks for continuing to hack away at this! This is a huge improvement, so it is much appreciated!

**Comment by ckato3** [comment]
It has been about 6 months since I submitted my pull request, but the merge to upstream has not progressed.

There are many changes, can you merge just SOME of them?

The master version has difficulties with the DJI P4 Multispectral, and there have been repeated reports of problems in the ODM community, which is not very desirable.

Is there anything I can do for merging my PullReq to Upstream ?

**Comment by Saijin-Naib** [comment]
Are you able to provide some A/B test scenarios with your fixes so we can evaluate them? It might help :)

**Comment by Saijin-Naib** [comment]
Was this superseded by another MR?

**Comment by ckato3** [comment]
In response to my pull request (multispectral branch), ODM administrators have not merged it into the master branch and have left it unmerged for more than 6 months.
Therefore, I have decided to close my pull request.

My multispectral branch is still being improved.
I continue to work on improving the algorithms and / or the accuracy of the numerical parameters in the code.

Once I determine that my code modifications have reached a certain level, then, 
If the ODM administrators want to merge, I will reopen my pull request.

**Comment by satas12825** [comment]
how can i apply this with WebODM

**Pull request closed without merging**
