### PR TITLE
Tower mode (OpenMVS update), fixes

### PR DESCRIPTION
**Pull request by pierotofy**
- Upgrade OpenMVS
- Fix pc-filter 0

OpenMVS has a novel tower mode feature which should improve tower reconstructions. I haven't been able to find a good dataset to test, but screenshots from the OpenMVS repo look very cool.

### CODE REVIEW

**Comment by pierotofy** [comment]
Closes #1682

**Comment by ckato3** [comment]
This OpenMVS upgrade has caused an error.

==========
[39m[INFO]    running "/code/SuperBuild/install/bin/OpenMVS/ReconstructMesh" -i "/code/odm_meshing/odm_mesh.dirty.ply" -o "/code/odm_meshing/odm_mesh.ply" --remove-spikes 0 --remove-spurious 20 --smooth 0 --target-face-num 400000 -v 0[0m
10:32:31 [App     ] OpenMVS x32 v2.2.0
10:32:31 [App     ] Build date: Aug 23 2023, 01:04:21
10:32:31 [App     ] CPU:  (10 cores)
10:32:31 [App     ] RAM: 76.56GB Physical Memory 8.00GB Virtual Memory
10:32:31 [App     ] OS: Linux 5.15.0-79-generic (aarch64)
10:32:31 [App     ] Disk: 
10:32:31 [App     ] warning: no SSE compatible CPU or OS detected
10:32:31 [App     ] Command line: ReconstructMesh -i /code/odm_meshing/odm_mesh.dirty.ply -o /code/odm_meshing/odm_mesh.ply --remove-spikes 0 --remove-spurious 20 --smooth 0 --target-face-num 400000 -v 0

Decimated faces 29364 (1.22%, 1s, ETA 2m)...
Decimated faces 60181 (2.51%, 1s, ETA 1m)...
Decimated faces 90536 (3.78%, 1s, ETA 49s)...

...


Decimated faces 2304488 (96.13%, 14s, ETA 595ms)...
Decimated faces 2325166 (97.00%, 14s, ETA 461ms)...
Decimated faces 2344658 (97.81%, 14s, ETA 335ms)...
Decimated faces 2363634 (98.60%, 15s, ETA 214ms)...
Decimated faces 2381837 (99.36%, 15s, ETA 97ms)... 
Decimated faces 2397190 (100%, 15s281ms)          Segmentation fault (core dumped)

===== Dumping Info for Geeks (developers need this to fix bugs) =====
Child returned 139
Traceback (most recent call last):
  File "/code/stages/odm_app.py", line 81, in execute
    self.first_stage.run()
  File "/code/opendm/types.py", line 440, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 440, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 440, in run
    self.next_stage.run(outputs)
  [Previous line repeated 3 more times]
  File "/code/opendm/types.py", line 406, in run
    self.process(self.args, outputs)
  File "/code/stages/odm_meshing.py", line 25, in process
    mesh.screened_poisson_reconstruction(tree.filtered_point_cloud,
  File "/code/opendm/mesh.py", line 200, in screened_poisson_reconstruction
    system.run('"{reconstructmesh}" -i "{infile}" '
  File "/code/opendm/system.py", line 127, in run
    raise SubprocessException("Child returned {}".format(retcode), retcode)
opendm.system.SubprocessException: Child returned 139

===== Done, human-readable information to follow... =====

[91m[ERROR]   Uh oh! Processing stopped because of strange values in the reconstruction. This is often a sign that the input data has some issues or the software cannot deal with it. Have you followed best practices for data acquisition? See https://docs.opendronemap.org/flying/[0m

**Comment by pierotofy** [comment]
Ugh, thanks @ckato3 

See https://github.com/OpenDroneMap/ODM/pull/1690

**Comment by miteshgarg** [comment]
Hi Guys, 
I am working on a problem to create a particularly good 3D point cloud of a telecommunication tower from the drone images.
Please help me to understand how can I use this Tower Mode feature for improvement of Tower reconstructions.
Is it a parameter which we can set to while running the ODM or is there any other way to use it?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by miteshgarg** [comment]
sure Piero 👍Thanks for you suggestionOn 31-Aug-2023 11:46 am, Piero Toffanin ***@***.***> wrote:
Could we move this conversation over to the forum at https://community.opendronemap.org? 🙏 The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! 👍

**Pull request merged**
