### PR TITLE
Thermal band support

### PR DESCRIPTION
**Pull request by pierotofy**
Adds support for thermal bands, including radiometric calibration to calculate absolute temperature values.

Currently tested with the MicaSense Altum test dataset: https://testhub1.dronedb.app/r/pierotofy/87dd21f97c3244f990e719132a1cfb7c

Different camera vendors will need different code logic for handling the conversion to temperature values.

### CODE REVIEW

**Comment by pierotofy** [comment]
image

**Comment by pierotofy** [comment]
image
image

**Comment by pierotofy** [comment]
Amazingly it works with thermal images that are 160x120.

**Comment by pierotofy** [comment]
We now have band descriptions carried forward in the GeoTIFFs too! 
image

**Comment by KeoChi** [comment]
Hello, I can not download the thermal dataset. Can you give a google drive link?

**Comment by ambarja** [comment]
Is available to do the radiometric calibration of the Anafi thermal images ?

**Pull request merged**
