### PR TITLE
Fix strange python launcher error when folder has spaces

### LINKED ISSUE #1569: Windows installation in non-default path causes error
> installed at a non-default path (in my user dir) and tried to run run.bat but it failed because it couldn't find geos_c.dll at ./venv/Library/bin/geos_c.dll .  Copying it from the shapely site-packages to that location solved it though

### PR DESCRIPTION
**Pull request by HeDo88TH**
This PR fixes the behavior of innosetup to use the windows short path when it contains spaces.
The issue seems to be related to https://github.com/pypa/setuptools/issues/216 and several others. I tested the same exact setup with newer python versions and they work fine. Unfortunately we are stuck with python 3.8 due to breaking changes in newer versions.

Bonus: added `vcpkg`, `venv`, `python38`, `dist` and `innosetup` folders to gitignore.

Closes #1569

### CODE REVIEW

**Comment by pierotofy** [comment]
Thanks. I'm a bit hesitant to accept this as a solution, it's my understanding that you're simply forcing users to install ODM to a path without spaces (via shortpath)? I also have concerns about that "Delete Folder" statement (potentially dangerous) and the ASCII encoding requirement (will this even work with non-ASCII characters in the path?)

If this issue was fixed in newer versions of Python, can't we just backport the patch?

For example, have you attempted to apply https://github.com/pypa/setuptools/pull/2697 ?

**Comment by HeDo88TH** [comment]
We abandoned the short path workaround in favour of merging the folders `python38` and `venv\Scripts`. 
It works and test pipeline runs!

**Comment by pierotofy** [comment]
Need to wait for https://gitlab.com/gitlab-org/gitlab/-/issues/402616 to test this (it's causing the ODM builds to fail).

```
2023-03-29T18:11:09.9728890Z     Performing download step (download, verify and extract) for 'ext_eigen'
2023-03-29T18:11:10.0050628Z     -- Downloading...
2023-03-29T18:11:10.0053940Z        dst='D:/a/ODM/ODM/SuperBuild/build/mvstexturing/elibs/ext_eigen/src/eigen-3.3.2.tar.gz'
2023-03-29T18:11:10.0054871Z        timeout='none'
2023-03-29T18:11:10.0056023Z        inactivity timeout='none'
2023-03-29T18:11:10.0057117Z     -- Using src='https://gitlab.com/libeigen/eigen/-/archive/3.3.2/eigen-3.3.2.tar.gz'
2023-03-29T18:11:10.8564153Z     -- verifying file...
2023-03-29T18:11:10.8565675Z            file='D:/a/ODM/ODM/SuperBuild/build/mvstexturing/elibs/ext_eigen/src/eigen-3.3.2.tar.gz'
2023-03-29T18:11:10.8657097Z     -- MD5 hash of
2023-03-29T18:11:10.8657908Z         D:/a/ODM/ODM/SuperBuild/build/mvstexturing/elibs/ext_eigen/src/eigen-3.3.2.tar.gz
2023-03-29T18:11:10.8659324Z       does not match expected value
2023-03-29T18:11:10.8660476Z         expected: '02edfeec591ae09848223d622700a10b'
2023-03-29T18:11:10.8661183Z           actual: '7b8ab470dbf9d22bf4adef60f9f8f4f2'
```

Not related to the changes here.

**Comment by HeDo88TH** [comment]
> Need to wait for https://gitlab.com/gitlab-org/gitlab/-/issues/402616 to test this (it's causing the ODM builds to fail).

They messed up some hashes 😢

**Comment by pierotofy** [comment]
Everything checks out, thanks!

**Pull request merged**
